### ISSUE TITLE
Install the roboto fonts on device by default

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#105]
Currently we're shipping them with gaia, but we want roboto to be the system default sans serif font.  It's also much slower to load fonts through httpd.js in the current setup.

**Comment by joneschrisg** [comment]
CC @fabricedesre 

Please close when landed.

**Comment by fabricedesre** [comment]
Pushed the OpenSans fonts :
https://github.com/cgjones/android-frameworks-base/commit/79dd33b406d4caca289682086f6dda24918caf42
