### ISSUE TITLE
B2G does not react for incoming call

### ISSUE THREAD

**Issue by ThinkerYzu** [andreasgal/B2G#107]
Implementation of telephony did receive incoming calls, but gaia does not.  There are some logical errors in gaia, they are logic of launching app and handling incoming call events.   We may also have to modify mozTelephony to pass more information for incoming call events; for example, call index.  With some workaround, we can accept an incoming call.  @kanru is working on this issue to provide a formal solution.

**Comment by joneschrisg** [comment]
https://github.com/andreasgal/gaia/pull/223 fixes some gaia bugs I found.  We have some additional bugs in the telephony backend in which it doesn't report incoming calls properly when navigator.mozTelephony is loaded after the call is received.  This will be landing soon with https://bugzilla.mozilla.org/show_bug.cgi?id=674726 .

Can you guys describe the issue with the call index?  If this is an issue with the telephony API, we should track it in bugzilla, probably as a followup to https://bugzilla.mozilla.org/show_bug.cgi?id=674726 .

**Comment by kanru** [comment]
Yap, https://github.com/andreasgal/gaia/pull/223 fixes the first two issues we found. And the last one is that the first incoming call after gaia starts isn't handled properly. Telephony pushed the call to liveCalls but dialer found zero. I'm not sure if it is the same issue you found.

**Comment by joneschrisg** [comment]
Yep! :)  https://bugzilla.mozilla.org/show_bug.cgi?id=674726#c35
