### ISSUE TITLE
event.data.split is not a function 

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#112]
Browser warning in the console.

E/GeckoConsole(   32): [JavaScript Error: "event.data.split is not a function" {file: "http://localhost:8888/apps/browser/webapi+apps.js" line: 39}]
E/GeckoConsole(   32): [JavaScript Error: "event.data.split is not a function" {file: "http://localhost:8888/apps/browser/webapi+apps.js" line: 39}]
E/GeckoConsole(   32): [JavaScript Error: "event.data.split is not a function" {file: "http://localhost:8888/apps/browser/webapi+apps.js" line: 39}]

**Comment by joneschrisg** [comment]
This is https://github.com/andreasgal/gaia/issues/221
