### ISSUE TITLE
WebGL: Can't get a usable WebGL context

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#113]
E/GeckoConsole(   32): [JavaScript Warning: "WebGL: Can't get a usable WebGL context" {file: "http://localhost:8888/apps/homescreen/js/scenegraph.js" line: 114}]
E/GeckoConsole(   32): [JavaScript Warning: "WebGL: Can't get a usable WebGL context" {file: "http://localhost:8888/apps/homescreen/js/scenegraph.js" line: 114}]

**Comment by joneschrisg** [comment]
Was this in the emulator?  The emulator doesn't support GLES 2.0, so this is expected.  We fall back on 2d canvas.

**Comment by arky** [comment]
Great! Thanks for the info.
