### ISSUE TITLE
this._db is null

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#115]
Another boot error: 

E/GeckoConsole(   32): [JavaScript Error: "this._db is null" {file: "http://localhost:8888/apps/homescreen/webapi+apps.js" line: 193}]

**Comment by joneschrisg** [comment]
For issues in gaia code (the HTML UI), please file at https://github.com/andreasgal/gaia/issues .

I transferred this issue to https://github.com/andreasgal/gaia/issues/239
