### ISSUE TITLE
W/AudioSystem( 5996): AudioPolicyService not published, waiting...

### ISSUE THREAD

**Issue by vingtetun** [andreasgal/B2G#123]
W/AudioSystem( 5996): AudioPolicyService not published, waiting...
I/ServiceManager( 5996): Waiting for service media.audio_policy...

Trying to use Audio in the Gaia UI freezes the main thread.

**Comment by vingtetun** [comment]
Here is the error I have when trying to launch mediaserver from the command line: 

link_image[1963]:  3584 could not load needed library 'libcameraservice.so' for 'mediaserver' (link_image[1963]:  3584 could not load needed library 'libcamera.so' for 'libcameraservice.so' (reloc_library[1312]:  3584 cannot locate '_ZN7android16CameraParameters20PIXEL_FORMAT_YUV420PE'...
))CANNOT LINK EXECUTABLE

**Comment by joneschrisg** [comment]
This is a regression from the state of at least a week or two ago; I can definitely confirm audio worked on my sgs2.

@vingtetun what android firmware image did you create your b2g build from?  You probably have an incompatible libcamera.so.

CC @mrbkap

**Comment by joneschrisg** [comment]
79d17d1e8685adc6a340bb67e7d122b7fc5bf406

**Comment by devwang-com** [comment]
I also met that MyService not published, waiting...

**Comment by d0n** [comment]
I'm facing the same problem - but i managed to fix it temporarily (on boot via adb shell). It had something to do with nvram. As is was starting nvram_daemon, nvram_agent_binder as well as agoldnvram. I was able to start the audioserver. As soon as that was working it bootet up correctly.
