### ISSUE TITLE
Add |make flash-maguro| target to top-level makefile

### ISSUE THREAD

**Issue by mvines** [andreasgal/B2G#126]
We probably want 'flash-maguro' and 'flash-only-maguro' targets added to the top-level makefile for consistency with the other devices

**Comment by joneschrisg** [comment]
Yes, we've been holding off on that until we're sure flashing won't brick the devices :).  Testing this week.

**Comment by mvines** [comment]
It'll be virtual impossible to inadvertently brick the device by loading a boot/system/userdata partition via fastboot.  I've loaded all sorts of goo over time.   Just hold down the volume down key during boot and LK will pop right back into fastboot mode.   The 'flash-crespo4g' target looks pretty much exactly what we want.   I haven't actually tried the recovery.img that B2G produces (hold down the up volume key during boot to enter recover mode FYI) but should be benign to load it with 'fastboot flashall -w'

**Comment by joneschrisg** [comment]
509c71a8e41e8178cc6c68ff02a10eea2025af23
