### ISSUE TITLE
Kill dalvik

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#128]
Step 2 in Operation Decaf.  We may have to do this along with #127, if the optimizer doesn't like empty files.

The scope of this work is less clear to me.  The end result should be removing the dalvik external repository.

**Comment by ThinkerYzu** [comment]
I have tried to remove zygote from init.rc.  It works fine for me.  Pull request #142 removes modules in Java, but it does not remove dalvik.  dalvik can be removed by adding it to the list of REMOVE_MODULES.

**Comment by ThinkerYzu** [comment]
https://github.com/michaelwu/clockworkmod_galaxys2_initramfs/pull/1 remove zygote from init.rc.

**Comment by michaelwu** [comment]
dalvik removed in https://github.com/andreasgal/B2G/commit/7f3b48e6808aa97940c329dc89d1a6621a6aca8f

One subdirectory of dalvik was left behind because removing it would upset a lot of code in framework/base, and the only thing really used there are headers. However, libdvm.so is dead.
