### ISSUE TITLE
mediaserver crashing, (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#132]
This is with a clean build of latest b2g.  Will poke.

I/DEBUG   ( 2562): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
I/DEBUG   ( 2562): Build fingerprint: 'samsung/full_galaxys2/galaxys2:2.3.5/GINGERBREAD/eng.cjones.20120112.192638:eng/test-keys'
I/DEBUG   ( 2562): pid: 2947, tid: 2947  >>> /system/bin/mediaserver <<<
I/DEBUG   ( 2562): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr a358134c
I/DEBUG   ( 2562):  r0 ffffffda  r1 fb580950  r2 00000016  r3 00000050
I/DEBUG   ( 2562):  r4 b000c134  r5 ffb58095  r6 a358134c  r7 be894a78
I/DEBUG   ( 2562):  r8 a80009fc  r9 a8001d8c  10 a80021ed  fp b0009468
I/DEBUG   ( 2562):  ip a80020d3  sp be894a78  lr b000382d  pc b0003820  cpsr a0000030
I/DEBUG   ( 2562):  d0  706a636573626974  d1  666f73637261672e
I/DEBUG   ( 2562):  d2  646f4d5f63697473  d3  74696c4c5f656c6f
I/DEBUG   ( 2562):  d4  0000000000000000  d5  0000000000000000
I/DEBUG   ( 2562):  d6  0000000000000000  d7  c18af96700000000
I/DEBUG   ( 2562):  d8  0000000000000000  d9  0000000000000000
I/DEBUG   ( 2562):  d10 0000000000000000  d11 0000000000000000
I/DEBUG   ( 2562):  d12 0000000000000000  d13 0000000000000000
I/DEBUG   ( 2562):  d14 0000000000000000  d15 0000000000000000
I/DEBUG   ( 2562):  d16 0000000000000000  d17 0000000000000000
I/DEBUG   ( 2562):  d18 0000000000000000  d19 0000000000000000
I/DEBUG   ( 2562):  d20 0000000000000000  d21 0000000000000000
I/DEBUG   ( 2562):  d22 0000000000000000  d23 0000000000000000
I/DEBUG   ( 2562):  d24 0000000000000000  d25 0000000000000000
I/DEBUG   ( 2562):  d26 0000000000000000  d27 0000000000000000
I/DEBUG   ( 2562):  d28 0000000000000000  d29 0000000000000000
I/DEBUG   ( 2562):  d30 0000000000000000  d31 0000000000000000
I/DEBUG   ( 2562):  scr 00000000
I/DEBUG   ( 2562): 
I/DEBUG   ( 2562):          #00  pc b0003820  /system/bin/linker
I/DEBUG   ( 2562):          #01  lr b000382d  /system/bin/linker
I/DEBUG   ( 2562): 
I/DEBUG   ( 2562): code around pc:
I/DEBUG   ( 2562): b0003800 90acf8d0 f8d44608 469210b4 ef56f7fd 
I/DEBUG   ( 2562): b0003810 30bcf8d4 5021f853 0129e014 0601eb08 
I/DEBUG   ( 2562): b0003820 0001f858 44484651 fef2f002 7b30b930 
I/DEBUG   ( 2562): b0003830 1e5a0903 d8012a01 b93189f1 60c0f8d4 
I/DEBUG   ( 2562): b0003840 5025f856 d1e82d00 4630462e e8bd46bd 
I/DEBUG   ( 2562): 
I/DEBUG   ( 2562): code around lr:
I/DEBUG   ( 2562): b000380c ef56f7fd 30bcf8d4 5021f853 0129e014 
I/DEBUG   ( 2562): b000381c 0601eb08 0001f858 44484651 fef2f002 
I/DEBUG   ( 2562): b000382c 7b30b930 1e5a0903 d8012a01 b93189f1 
I/DEBUG   ( 2562): b000383c 60c0f8d4 5025f856 d1e82d00 4630462e 
I/DEBUG   ( 2562): b000384c e8bd46bd bf0087f0 4ff0e92d f8dfb08b 
I/DEBUG   ( 2562): 
I/DEBUG   ( 2562): stack:
I/DEBUG   ( 2562):     be894a38  b000fc98  
I/DEBUG   ( 2562):     be894a3c  b000fc98  
I/DEBUG   ( 2562):     be894a40  b000c24c  
I/DEBUG   ( 2562):     be894a44  00000000  
I/DEBUG   ( 2562):     be894a48  b00102d4  
I/DEBUG   ( 2562):     be894a4c  be894ab4  
I/DEBUG   ( 2562):     be894a50  b000fc98  
I/DEBUG   ( 2562):     be894a54  00000015  
I/DEBUG   ( 2562):     be894a58  80a0bfd4  /system/lib/libseccameraadaptor.so
I/DEBUG   ( 2562):     be894a5c  0001d058  
I/DEBUG   ( 2562):     be894a60  be894a90  
I/DEBUG   ( 2562):     be894a64  80a00000  /system/lib/libseccameraadaptor.so
I/DEBUG   ( 2562):     be894a68  b000c24c  
I/DEBUG   ( 2562):     be894a6c  b000c134  
I/DEBUG   ( 2562):     be894a70  df002777  
I/DEBUG   ( 2562):     be894a74  e3a070ad  
I/DEBUG   ( 2562): #00 be894a78  00000016  
I/DEBUG   ( 2562):     be894a7c  b000c134  
I/DEBUG   ( 2562):     be894a80  0b495926  
I/DEBUG   ( 2562):     be894a84  be894aa8  
I/DEBUG   ( 2562):     be894a88  b000c134  
I/DEBUG   ( 2562):     be894a8c  a80021ed  /system/lib/libcameraservice.so
I/DEBUG   ( 2562):     be894a90  0000001d  
I/DEBUG   ( 2562):     be894a94  b0003895  /system/bin/linker
I/DEBUG   ( 2562):     be894a98  80a0372c  /system/lib/libseccameraadaptor.so
I/DEBUG   ( 2562):     be894a9c  be894ab4  
I/DEBUG   ( 2562):     be894aa0  00000001  
I/DEBUG   ( 2562):     be894aa4  b000c24c  
I/DEBUG   ( 2562):     be894aa8  b000fc98  
I/DEBUG   ( 2562):     be894aac  b000fc98  
I/DEBUG   ( 2562):     be894ab0  b000c134  
I/DEBUG   ( 2562):     be894ab4  00000000  
I/DEBUG   ( 2562):     be894ab8  b00102d4  
I/DEBUG   ( 2562):     be894abc  be894b24

**Comment by qdot** [comment]
I had something similar happen today, mediaserver but different libraries, on a build after an update. make clean && make gonk && make cleared it up.

**Comment by joneschrisg** [comment]
I had a working build, then I followed those steps, and then I dint.

But I'll give it a go again.

**Comment by joneschrisg** [comment]
Yeah, reclean etc. gets me the same errors.  Will try a mrproper when I get the chance, unless someone else hits this in the meantime and we need to debug.

**Comment by joneschrisg** [comment]
OK, clean, reconfigure, and then full reflash (kernel+userspace) made this go away.  Sigh.

**Comment by joneschrisg** [comment]
(And audio still works.)
