### ISSUE TITLE
'build' target has broken dependencies

### ISSUE THREAD

**Issue by mvines** [andreasgal/B2G#133]
Current target::

```
build: gecko gecko-install-hack gonk
```

Since there is no expressed dependency between the gecko-install-hack and gonk targets in the top-level Makefile, parallel makes can and will begin 'gonk' before completing 'gecko-install-hack'.  This results in badness like a new system.img being constructed by 'gonk' and then getting whacked by 'gecko-install-hack'.

Here's one way to fix this

```
build: gecko-install-hack
    $(MAKE) gonk
```

(gecko-install-hack already depends on gecko, so the gecko target can be dropped.)

**Comment by michaelwu** [comment]
Please see https://github.com/andreasgal/B2G/issues/118

FWIW, https://github.com/andreasgal/B2G/blob/master/Makefile#L9 sets the -jN flag used when building gecko and gonk, so we do parallel make by default. (though it may not be a good number of parallel makes for your system)

**Comment by mvines** [comment]
Yep, thanks.  I run at around -j32 usually.

**Comment by mvines** [comment]
d1ebcbec1dda65128744a888321085a999326ec5
