### ISSUE TITLE
make gonk can't find libz?

### ISSUE THREAD

**Issue by mimperatore** [andreasgal/B2G#136]
Hi there.  Has anyone run unto this problem?  I can't seem to find any reference to it elsewhere.  (See output below).

I do have various libz.so\* and libz.a's on the system:

marco@marco-VirtualBox:~/b2g/B2G$ locate libz | grep 'libz.'
/home/marco/b2g/B2G/glue/gonk/development/ndk/platforms/android-3/arch-arm/lib/libz.so
/home/marco/b2g/B2G/glue/gonk/out/host/linux-x86/obj/NOTICE_FILES/src/lib/libz.a.txt
/home/marco/b2g/B2G/glue/gonk/out/host/linux-x86/obj/STATIC_LIBRARIES/libz_intermediates/libz.a
/home/marco/b2g/B2G/glue/gonk/out/target/product/generic/obj/NOTICE_FILES/src/system/lib/libz.a.txt
/home/marco/b2g/B2G/glue/gonk/out/target/product/generic/obj/NOTICE_FILES/src/system/lib/libz.so.txt
/home/marco/b2g/B2G/glue/gonk/prebuilt/linux-x86/toolchain/i686-linux-glibc2.7-4.4.3/sysroot/usr/lib/libz.a
/home/marco/b2g/B2G/glue/gonk/prebuilt/linux-x86/toolchain/i686-linux-glibc2.7-4.4.3/sysroot/usr/lib/libz.so
/home/marco/b2g/B2G/glue/gonk/prebuilt/linux-x86/toolchain/i686-linux-glibc2.7-4.4.3/sysroot/usr/lib/libz.so.1
/home/marco/b2g/B2G/glue/gonk/prebuilt/linux-x86/toolchain/i686-linux-glibc2.7-4.4.3/sysroot/usr/lib/libz.so.1.2.3.3
/home/marco/b2g/B2G/glue/gonk/prebuilt/ndk/android-ndk-r4/platforms/android-3/arch-arm/usr/lib/libz.so
/home/marco/b2g/B2G/glue/gonk/prebuilt/ndk/android-ndk-r4/platforms/android-4/arch-arm/usr/lib/libz.so
/home/marco/b2g/B2G/glue/gonk/prebuilt/ndk/android-ndk-r4/platforms/android-5/arch-arm/usr/lib/libz.so
/home/marco/b2g/B2G/glue/gonk/prebuilt/ndk/android-ndk-r4/platforms/android-8/arch-arm/usr/lib/libz.so
/lib/i386-linux-gnu/libz.so.1
/lib/i386-linux-gnu/libz.so.1.2.3.4
/lib/x86_64-linux-gnu/libz.so.1
/lib/x86_64-linux-gnu/libz.so.1.2.3.4
/usr/lib/x86_64-linux-gnu/libz.a
/usr/lib/x86_64-linux-gnu/libz.so
/usr/lib32/libz.so.1
/usr/lib32/libz.so.1.2.3.4

marco@marco-VirtualBox:~/b2g/B2G$ make gonk
rm -rf /home/marco/b2g/B2G/glue/gonk/out/target/product/generic/system/home
mkdir -p /home/marco/b2g/B2G/glue/gonk/out/target/product/generic/system/home
cp -r gaia/\* /home/marco/b2g/B2G/glue/gonk/out/target/product/generic/system/home
rm -rf /home/marco/b2g/B2G/glue/gonk/out/target/product/generic/system/b2g/defaults/profile
mkdir -p /home/marco/b2g/B2G/glue/gonk/out/target/product/generic/system/b2g/defaults
cp -r gaia/profile /home/marco/b2g/B2G/glue/gonk/out/target/product/generic/system/b2g/defaults
including device/samsung/crespo4g/vendorsetup.sh
including device/samsung/crespo/vendorsetup.sh
including device/samsung/galaxys2/vendorsetup.sh
including device/toro/maguro/vendorsetup.sh
# 

PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=2.3.5
TARGET_PRODUCT=generic
TARGET_BUILD_VARIANT=eng
TARGET_SIMULATOR=false
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
HOST_ARCH=x86
HOST_OS=linux
HOST_BUILD_TYPE=release
# BUILD_ID=GINGERBREAD
# 

PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=2.3.5
TARGET_PRODUCT=generic
TARGET_BUILD_VARIANT=eng
TARGET_SIMULATOR=false
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
HOST_ARCH=x86
HOST_OS=linux
HOST_BUILD_TYPE=release
# BUILD_ID=GINGERBREAD

find: `frameworks/base/frameworks/base/docs/html': No such file or directory
find:`out/target/common/docs/gen': No such file or directory
find: `frameworks/base/frameworks/base/docs/html': No such file or directory
find:`out/target/common/docs/gen': No such file or directory
find: `frameworks/base/frameworks/base/docs/html': No such file or directory
find:`out/target/common/docs/gen': No such file or directory
find: `frameworks/base/frameworks/base/docs/html': No such file or directory
find:`out/target/common/docs/gen': No such file or directory
find: `frameworks/base/frameworks/base/docs/html': No such file or directory
find:`out/target/common/docs/gen': No such file or directory
make[1]: Entering directory `/home/marco/b2g/B2G/glue/gonk'
Install: out/host/linux-x86/framework/apicheck.jar
Install: out/host/linux-x86/framework/clearsilver.jar
Install: out/host/linux-x86/lib/libneo_util.so
Copying: out/target/common/obj/JAVA_LIBRARIES/core_intermediates/emma_out/lib/classes-jarjar.jar
Install: out/host/linux-x86/framework/dx.jar
host Executable: aapt (out/host/linux-x86/obj/EXECUTABLES/aapt_intermediates/aapt)
Install: out/host/linux-x86/bin/aidl
Install: out/host/linux-x86/bin/apicheck
target Prebuilt:  (out/target/product/generic/system/usr/share/zoneinfo/zoneinfo.dat)
target Prebuilt:  (out/target/product/generic/system/usr/share/zoneinfo/zoneinfo.idx)
target Prebuilt:  (out/target/product/generic/system/usr/share/zoneinfo/zoneinfo.version)
Copy: out/host/linux-x86/usr/share/zoneinfo/zoneinfo.dat
Copy: out/host/linux-x86/usr/share/zoneinfo/zoneinfo.idx
Copy: out/host/linux-x86/usr/share/zoneinfo/zoneinfo.version
target Prebuilt:  (out/target/product/generic/system/etc/security/cacerts.bks)
target Prebuilt:  (out/target/product/generic/system/usr/keylayout/tuttle2.kl)
target Prebuilt:  (out/target/product/generic/system/bin/am)
target Prebuilt:  (out/target/product/generic/system/bin/bmgr)
target Prebuilt:  (out/target/product/generic/system/bin/input)
target Prebuilt:  (out/target/product/generic/system/bin/ime)
target Prebuilt:  (out/target/product/generic/system/bin/svc)
target Prebuilt:  (out/target/product/generic/system/bin/pm)
target Prebuilt:  (out/target/product/generic/system/usr/keylayout/qwerty.kl)
target Prebuilt:  (out/target/product/generic/system/usr/keylayout/AVRCP.kl)
/usr/bin/ld: cannot find -lz
collect2: ld returned 1 exit status
make[1]: *** [out/host/linux-x86/obj/EXECUTABLES/aapt_intermediates/aapt] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory`/home/marco/b2g/B2G/glue/gonk'
make: **\* [gonk] Error 2

**Comment by joneschrisg** [comment]
I haven't seen this before.  Did you |make config-qemu| ?

**Comment by mimperatore** [comment]
Yep.  Ran 'make config-qemu' and it did not complain about anything.  I'm using a fresh install of Ubuntu 11.10 and followed the instructions on the INSTALL page for the Android Emulator setup.

**Comment by mimperatore** [comment]
Sorry, didn't mean to close...

**Comment by ThinkerYzu** [comment]
Please show me the output of "ldconfig -p" for linux.  It would more accurate than locate.

**Comment by mimperatore** [comment]
marco@marco-VirtualBox:~/b2g/B2G/glue/gonk$ ldconfig -p | grep libz\.
libz.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libz.so.1
libz.so.1 (libc6) => /usr/lib32/libz.so.1
libz.so.1 (libc6) => /lib/i386-linux-gnu/libz.so.1
libz.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libz.so

On Fri, Jan 20, 2012 at 5:16 AM, ThinkerYzu <
reply@reply.github.com

**Comment by ThinkerYzu** [comment]
It seems libz is ready for being used.  It would be better if you can provide exactly command and arguments.  You can got it by running |echo "SHOW_COMMANDS:=true" >> glue/gonk/buildspec.mk|.  Then, |make gonk| would show commands and arguments.

**Comment by michaelwu** [comment]
Try installing 32bit static zlib
