### ISSUE TITLE
emulator build broken

### ISSUE THREAD

**Issue by jonallengriffin** [andreasgal/B2G#139]
The emulator hasn't built correctly since 9e52089ddab0cdba501dd3aa2570eb697aed794d; see http://builder.boot2gecko.org/.  The build error is:

target thumb C++: libstagefright_omx <= frameworks/base/media/libstagefright/omx/OMXComponentBase.cpp
frameworks/base/services/camera/libcameraservice/CameraHardwareStub.cpp: In static member function 'static android::spandroid::CameraHardwareInterface android::CameraHardwareStub::createInstance()':
frameworks/base/services/camera/libcameraservice/CameraHardwareStub.cpp:385: error: cannot allocate an object of abstract type 'android::CameraHardwareStub'
frameworks/base/services/camera/libcameraservice/CameraHardwareStub.h:30: note:   because the following virtual functions are pure within 'android::CameraHardwareStub':
frameworks/base/include/camera/CameraHardwareInterface.h:134: note:     virtual android::status_t android::CameraHardwareInterface::getBufferInfo(android::spandroid::IMemory&, size_t_)
frameworks/base/include/camera/CameraHardwareInterface.h:139: note:     virtual void android::CameraHardwareInterface::encodeData()
frameworks/base/include/camera/CameraHardwareInterface.h:232: note:     virtual android::status_t android::CameraHardwareInterface::takeLiveSnapshot()
frameworks/base/services/camera/libcameraservice/CameraHardwareStub.cpp: In function 'android::spandroid::CameraHardwareInterface android::HAL_openCameraHardware(int)':
frameworks/base/services/camera/libcameraservice/CameraHardwareStub.cpp:405: error: declaration of C function 'android::spandroid::CameraHardwareInterface android::HAL_openCameraHardware(int)' conflicts with
frameworks/base/include/camera/CameraHardwareInterface.h:245: error: previous declaration 'android::spandroid::CameraHardwareInterface android::HAL_openCameraHardware(int, int)' here
make[1]: *_\* [out/target/product/generic/obj/STATIC_LIBRARIES/libcamerastub_intermediates/CameraHardwareStub.o] Error 1
make[1]: **\* Waiting for unfinished jobs....
target thumb C++: libstagefright_omx <= frameworks/base/media/libstagefright/omx/OMXNodeInstance.cpp
target thumb C++: libstagefright_omx <= frameworks/base/media/libstagefright/omx/OMXMaster.cpp
make[1]: Leaving directory `/home/jgriffin/jB2G/glue/gonk'
make: **\* [gonk] Error 2

**Comment by mvines** [comment]
One way to resolve this is to patch CameraHardwareStub.cpp to include the extra symbols that were added in
https://github.com/cgjones/android-frameworks-base/commit/0ffff0da5944d7581d716e377cf21e9b696dad0f

Here's an implementation to poach from: https://www.codeaurora.org/gitweb/quic/la/?p=platform/frameworks/base.git;a=blob;f=services/camera/libcameraservice/CameraHardwareStub.cpp;h=bd3b5eaac22af91edea85bd05a9b3af9aec4a787;hb=gingerbread_chocolate

**Comment by shianyow** [comment]
After patching CameraHardwareStub.h and CameraHardwareStub.cpp, it solved the compiling error issue.
@mvines would you like to commit the patch?

**Comment by shianyow** [comment]
Just found that @kanru already sent a pull request to select camera hardware interface by target at https://github.com/cgjones/android-frameworks-base/pulls
Let's wait it to be merged.

**Comment by joneschrisg** [comment]
http://builder.boot2gecko.org/ says this is fixed by ac610f4.

**Comment by rainti** [comment]
how to resolve this problem
