### ISSUE TITLE
"C compiler cannot create executables" during make

### ISSUE THREAD

**Issue by jonallengriffin** [andreasgal/B2G#143]
This occurs even when running 'make gonk' before 'make'.  The problem seems to have been introduced at https://github.com/andreasgal/B2G/commit/18ae0c39a4bdd2d6303b0878d6e1f7f49d8feb74.  

The exact error is:

checking for gcc... /data/gitbuilder/build/glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-gcc
checking whether the C compiler (/data/gitbuilder/build/glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-gcc -mandroid -fno-short-enums -fno-exceptions -mandroid -L/data/gitbuilder/build/glue/gonk/out/target/product/generic/obj/lib -Wl,-rpath-link=/data/gitbuilder/build/glue/gonk/out/target/product/generic/obj/lib --sysroot=/data/gitbuilder/build/glue/gonk/out/target/product/generic/obj/ -llog ) works... no

```
error: configure: installation or configuration problem: C compiler cannot create executables. 
```

**Comment by michaelwu** [comment]
Can you post the config.log from the obj dir?

**Comment by jonallengriffin** [comment]
config.log is:

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

configure:1042: checking host system type
configure:1063: checking target system type
configure:1081: checking build system type
configure:1161: checking for gawk
configure:1397: checking for perl5
configure:1397: checking for perl
configure:1762: checking for host c compiler
configure:1768: checking for gcc
configure:1803: checking for host c++ compiler
configure:1809: checking for c++
configure:1861: checking for ranlib
configure:1896: checking for ar
configure:1931: checking whether the host c compiler (gcc    ) works
configure:1940: gcc -c   -DANDROID -I/data/gitbuilder/build/glue/gonk/bionic/libc/include/ -I/data/gitbuilder/build/glue/gonk/bionic/libc/kernel/common -I/data/gitbuilder/build/glue/gonk/bionic/libc/arch-arm/include -I/data/gitbuilder/build/glue/gonk/bionic/libc/kernel/arch-arm -I/data/gitbuilder/build/glue/gonk/bionic/libm/include -I/data/gitbuilder/build/glue/gonk/frameworks/base/opengl/include -I/data/gitbuilder/build/glue/gonk/frameworks/base/native/include -I/data/gitbuilder/build/glue/gonk/hardware/libhardware/include -I/data/gitbuilder/build/glue/gonk/hardware/libhardware_legacy/include -I/data/gitbuilder/build/glue/gonk/system/core/include -I/data/gitbuilder/build/glue/gonk/bionic -I/data/gitbuilder/build/glue/gonk/frameworks/base/include -I/data/gitbuilder/build/glue/gonk/ndk/sources/cxx-stl/stlport/stlport/  conftest.c 1>&5
configure:1955: checking whether the host c++ compiler (c++    ) works
configure:1964: c++ -c   -DANDROID -I/data/gitbuilder/build/glue/gonk/bionic/libc/include/ -I/data/gitbuilder/build/glue/gonk/bionic/libc/kernel/common -I/data/gitbuilder/build/glue/gonk/bionic/libc/arch-arm/include -I/data/gitbuilder/build/glue/gonk/bionic/libc/kernel/arch-arm -I/data/gitbuilder/build/glue/gonk/bionic/libm/include -I/data/gitbuilder/build/glue/gonk/frameworks/base/opengl/include -I/data/gitbuilder/build/glue/gonk/frameworks/base/native/include -I/data/gitbuilder/build/glue/gonk/hardware/libhardware/include -I/data/gitbuilder/build/glue/gonk/hardware/libhardware_legacy/include -I/data/gitbuilder/build/glue/gonk/system/core/include -I/data/gitbuilder/build/glue/gonk/bionic -I/data/gitbuilder/build/glue/gonk/frameworks/base/include -I/data/gitbuilder/build/glue/gonk/ndk/sources/cxx-stl/stlport/stlport/  conftest.c 1>&5
configure:1984: checking for /data/gitbuilder/build/glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-gcc
configure:2018: checking for gcc
configure:2131: checking whether the C compiler (/data/gitbuilder/build/glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-gcc -mandroid -fno-short-enums -fno-exceptions  -mandroid -L/data/gitbuilder/build/glue/gonk/out/target/product/generic/obj/lib -Wl,-rpath-link=/data/gitbuilder/build/glue/gonk/out/target/product/generic/obj/lib --sysroot=/data/gitbuilder/build/glue/gonk/out/target/product/generic/obj/ -llog ) works
configure:2147: /data/gitbuilder/build/glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-gcc -o conftest -mandroid -fno-short-enums -fno-exceptions  -DANDROID -I/data/gitbuilder/build/glue/gonk/bionic/libc/include/ -I/data/gitbuilder/build/glue/gonk/bionic/libc/kernel/common -I/data/gitbuilder/build/glue/gonk/bionic/libc/arch-arm/include -I/data/gitbuilder/build/glue/gonk/bionic/libc/kernel/arch-arm -I/data/gitbuilder/build/glue/gonk/bionic/libm/include -I/data/gitbuilder/build/glue/gonk/frameworks/base/opengl/include -I/data/gitbuilder/build/glue/gonk/frameworks/base/native/include -I/data/gitbuilder/build/glue/gonk/hardware/libhardware/include -I/data/gitbuilder/build/glue/gonk/hardware/libhardware_legacy/include -I/data/gitbuilder/build/glue/gonk/system/core/include -I/data/gitbuilder/build/glue/gonk/bionic -I/data/gitbuilder/build/glue/gonk/frameworks/base/include -I/data/gitbuilder/build/glue/gonk/ndk/sources/cxx-stl/stlport/stlport/  -mandroid -L/data/gitbuilder/build/glue/gonk/out/target/product/generic/obj/lib -Wl,-rpath-link=/data/gitbuilder/build/glue/gonk/out/target/product/generic/obj/lib --sysroot=/data/gitbuilder/build/glue/gonk/out/target/product/generic/obj/ -llog  conftest.c  -lstlport 1>&5
/data/gitbuilder/build/glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/../../../../arm-eabi/bin/ld: error: cannot find -lc
/data/gitbuilder/build/glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/../../../../arm-eabi/bin/ld: error: cannot find -ldl
/data/gitbuilder/build/glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/../../../../arm-eabi/bin/ld: error: cannot find -llog
/data/gitbuilder/build/glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/../../../../arm-eabi/bin/ld: error: cannot find -lstlport
/data/gitbuilder/build/glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/../../../../arm-eabi/bin/ld: /data/gitbuilder/build/glue/gonk/out/target/product/generic/obj//lib/crtbegin_dynamic.o:(.text+0x10): error: undefined reference to '__libc_init'
collect2: ld returned 1 exit status
configure: failed program was:

#line 2142 "configure"
#include "confdefs.h"

main(){return(0);}

**Comment by michaelwu** [comment]
I just disabled a build feature that recently landed that may be causing build problems. Can you pull and try again?

**Comment by jonallengriffin** [comment]
If you mean https://github.com/andreasgal/B2G/commit/9463e97ad6306eb5cc38a15bfa4eadddc8ce186c, it has the same issue, see http://builder.boot2gecko.org/log.cgi?log=9463e97ad6306eb5cc38a15bfa4eadddc8ce186c

**Comment by michaelwu** [comment]
Oh ok. So, the error we care about isn't actually "error: configure: installation or configuration problem: C compiler cannot create executables. ", but the one above it - "error: frameworks/base/services/camera/libcameraservice/CameraHardwareStub.cpp:385: cannot allocate an object of abstract type 'android::CameraHardwareStub' ". This suggests that one of the recent maguro camera changes caused a regression on qemu.

**Comment by jonallengriffin** [comment]
This may be a dupe of https://github.com/andreasgal/B2G/issues/139, but the errors are a bit different.

**Comment by mvines** [comment]
This build bug has existed for a while now, and is not related to the commit referenced in the initial comment on this issue.  "make gecko" needs stuff from glue/gonk/out/..., and without running "make gonk" first in a clean workspace then we get that obscure C compiler error.   "make gecko" prolly needs to be shimmed into an Android.mk under glue/gonk somewhere to resolve this circular build dep.

**Comment by jonallengriffin** [comment]
> and without running "make gonk" first in a clean workspace then we get that obscure C compiler error.

This isn't the same problem; it occurs when doing 'make' after 'make gonk'.

**Comment by jonallengriffin** [comment]
This is fixed now:  http://builder.boot2gecko.org/
