### ISSUE TITLE
Emulator-to-emulator SMS not working

### ISSUE THREAD

**Issue by jonallengriffin** [andreasgal/B2G#151]
Manually attempting to send an SMS from one emulator to another causes the sending emulator to hang with no errors in logcat.  This blocks adding an automated test for this.

To reproduce:

1 - launch two emulators.
2 - in one emulator, launch the SMS app, and enter the second emulator's port number (typically 5556) in the ''to" field.
3 - add some message, then click Send

Results:  busy animation appears indefinitely; emulator becomes unresponsive.  logcat shows no entries.

@malini, @jhammink

**Comment by philikon** [comment]
This is a combination of https://bugzilla.mozilla.org/show_bug.cgi?id=720643 and https://github.com/andreasgal/gaia/issues/325.
