### ISSUE TITLE
Integrate a pre-built gdb into gonk that's known to work with b2g

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#152]
We can grab prebuilt binaries from anywhere, as long as we leave a link to the source they were built from.  I've had good results with 

http://developer.download.nvidia.com/tegra/files/tegra-gdb-20100902.zip

which includes the patch against upstream gdb (IIRC).

It would be worth re-trying the pre-installed gdb that comes with android to see how well it works.  I have not historically had good results with it.

For the first landing here, let's get the following set up:
- the nvidia gdb host binary installed into some kind of host-tools directory.  It doesn't really matter where this is.
- the nvidia gdbserver guest binary installed on device.  I think there may already be a gdbserver installed, so we want to makes sure to replace that.

There's some more work we can do for a second landing, but this is the really important part.

**Comment by shianyow** [comment]
The nVidia gdb/gdbserver have been put to following locations:
- gdb -> glue/gonk/prebuilt/linux-x86/tegra-gdb/arm-eabi-gdb
- gdbserver -> glue/gonk/prebuilt/android-arm/gdbserver/gdbserver

The original gdbserver was replaced by nvidia gdbserver for now.
