### ISSUE TITLE
'error: do_inode_allocate_extents: Failed to allocate 36511 blocks'

### ISSUE THREAD

**Issue by jaoo** [andreasgal/B2G#154]
This error appears on my workspace when building B2G for maguro. How I came into this error was after |make config-maguro && make gonk| commands.

**Comment by ThinkerYzu** [comment]
@jaoo had run gonk with showcommands.  The log is http://pastebin.com/JBwjDNBu .  And, he find libwebcore.so is 143MB of 313MB total.  I think some one should remove webkit from being built.

**Comment by oteo** [comment]
As libwebcore.so is that big and it is not needed we have removed it manually by changing mkuserimg.sh.

When trying to reflash the device it fails:

FAILED

Device product is 'MSM7627A_SKU3'.
Update requires 'MSM7627A_SKU1'.

It looks like there is device product version problem.

The full result is available at:

http://pastebin.com/cxKqDfaR

**Comment by michaelwu** [comment]
I don't have webcore built here, and I don't actually see webkit in the tree. It should've been removed already.

**Comment by joneschrisg** [comment]
Yes, we removed webkit a loooong time ago.  Among lots of other stuff.

If you don't have anything in your b2g tree that you don't mind bring deleted,

$ make mrproper

will make sure your local directory is 100% the same as the remote repository at the revision you have checked out.

**Comment by jaoo** [comment]
Yes, you are right. It's quite strange to find that library still in the tree. I'll run rmproper and build again. I know about the powerful of that command. Once it deleted all my local scripts. xD. What about the different product/firmware version?

**Comment by joneschrisg** [comment]
Oh sorry, missed that.  we can auto detect this during configure and set a variable where BoardConfig.mk can pick it up.

@michaelwu might be able to help, or talk to someone who can.

**Comment by jaoo** [comment]
Solved. There were still some Android modules in my local working copy of B2G. This is quite strange because |make mrproper| does not remove those modules. Among them I had v8/, webkit/ and others. Thanks everybody for your help.

**Comment by oteo** [comment]
Los diseos de algunas pantallas, como detalles de Contacto y edicin de Contacto , son distintas ahora en la UX debido a algunos de los cambios implementados ayer tras el feedback de UX pero la funcionalidad, en s, es la misma.

Saludos

---

Este mensaje se dirige exclusivamente a su destinatario. Puede consultar nuestra poltica de envo y recepcin de correo electrnico en el enlace situado ms abajo.
This message is intended exclusively for its addressee. We only send and receive email on the basis of the terms set out at
http://www.tid.es/ES/PAGINAS/disclaimer.aspx

**Comment by oteo** [comment]
De: CARLOS ENRIQUE GOMEZ GOMEZ <carlosg@tid.es<mailto:carlosg@tid.es>>
Fecha: Tue, 6 Mar 2012 17:36:32 +0100
Para: FERNANDO JIMENEZ MORENO <ferjm@tid.es<mailto:ferjm@tid.es>>
CC: M ANGELES OTEO MARTINEZ <oteo@tid.es<mailto:oteo@tid.es>>, RUBEN GONZALEZ ALONSO <rga@tid.es<mailto:rga@tid.es>>, Jose Antonio Olivera Ortega <reply@reply.github.com<mailto:reply@reply.github.com>>, DANIEL JESUS COLOMA BAIGES <dcoloma@tid.es<mailto:dcoloma@tid.es>>, Guillermo Lpez Leal <gll@tid.es<mailto:gll@tid.es>>, ANA MARIA ALARCON SANCHEZ <amas@tid.es<mailto:amas@tid.es>>
Asunto: Re: Peticiones al EPG para OWD

Hola Fernando,

Buenas a todos,

El 06/03/12 12:50, FERNANDO JIMENEZ MORENO escribi:
Pongo en copia a Guillermo, que es quien est trasteando con Gerrit.

On 06/03/2012, at 12:47, Fernando Jimnez wrote:

Hola,

disculpad la tardanza en responder.

On 05/03/2012, at 13:44, Carlos E. Gmez Gmez wrote:

Hola Maria Angeles,

El 02/03/12 14:48, M ANGELES OTEO MARTINEZ escribi:
Hola Carlos,
Una cosilla, si la fecha es el 15 de Marzo, migraremos ya directamente en esa fecha, no vamos a migrar 2 veces no? Adems hasta os serviremos de conejillos de india ;)
   Creo que lo ms cmodo es esperar al 15 de Marzo
Ok.

De todas formas, al pasar a esa infraestructura no significar que no podamos tener nuestro cdigo tb en privado no?
   Estar en privado, pero CUIDADO, hay que poner que el cdigo es PRIVADO.
Ok.

Otra cosa, en la reunin que hemos tenido con el equipo hemos estado hablando de organizar de distinta forma nuestros ramas master y desarrollo, tal y como explicamos en esta wiki que ha hecho Fernando:
http://wikis.hi.inet/owd/index.php/Git_Workflow
    El TAC encarg a un grupo que definiera el flujo de trabajo para GIT (https://gittid.hi.inet/emc2-dyna/git-info/wiki/). En cuanto a compartir cdigo sin pasar por el repositorio central es ms propenso a errores, a no ser que todo el equipo tenga una experiencia muy alta en GIT.
Efectivamente. De hecho el workflow de nuestra wiki est basado en uno de los enlaces que propone el TAC con ligeras modificaciones.
Respecto a lo de la propensin a errores al compartir cdigo entre clones, no veo tal problema En cualquier caso, es una prctica poco comn de momento y fcilmente sustituible por el intercambio de parches.
El problema creo que surge si hay falta de experencia en el manejo de GIT por parte de algn miembro del equipo.

Igualmente, el problema que pueda tener la gente con git es siempre inicial. Pueden tener los mismos problemas con SVN u otro gestor de cdigo centralizado. De hecho, con sistemas centralizados hay ms problemas, sobre todo en proyectos donde varias personas trabajan en diferentes caractersticas (que se pueden desarrollar en diferentes ramas) y al final se quiere hacer un merge. Adems git permite repositorios locales o entre pares, cosa que SVN no y requiere siempre algo linea y centralizado o te vuelves loco.

Tambin hemos estado hablando de Revisin del Cdigo y de la herramienta Gerrit
http://gerrit-documentation.googlecode.com/svn/Documentation/2.2.2/intro-quick.html
A lo mejor, Ruben, t nos puedes ayudar con esto: dais soporte de dicha herramienta? se podra integrar con el Github?
Utilizando github ya se pueden hacer revisiones de cdigo sin necesidad de utilizar esta herramienta. Se puede utilizar la funcionalidad Pull Request de GitHub(ejemplo  https://gittid.hi.inet/connect/connect-api/pull/26), teniendo en cuenta que esta funcionalidad no impide hacer un commit al master sin que se haya hecho la pertinente revisin.
Personalmente, quiz, en parte, por desconocimiento, veo un poco limitada la herramienta de 'pull request' de Github para revisiones de cdigo.
Si no me equivoco, respecto a lo que comentas, se podran limitar los privilegios de push al trunk otorgando dichos permisos nicamente a los integradores/reviewers. El resto de desarrolladores (sin permisos de escritura en el trunk) podran trabajar en sus forks, haciendo pull requests y actualizando desde el upstream conforme fuese necesario.
En cualquier caso, por lo poco que hemos visto hasta ahora, Gerrit proporciona funcionalidad que podra venirnos bastante bien y que estamos poniendo a punto. Por poner un ejemplo, tras realizar una review, podemos lanzar un script para verificar, mediante la ejecucin de nuestros tests unitarios en hudson, que el patch revisado no 'rompe' nada e, incluso, que cumple nuestro coding style (estamos haciendo scripts para ello). Con esto, antes de hacer el push definitivo al trunk (que lo realizara el bot del propio Gerrit) obtendramos una revisin manual y una verificacin automtica del parche a subir. Por otra parte, esta herramienta nos permite definir de manera sencilla grupos con privilegios muy definidos (push, merge...), limitando las acciones susceptibles de provocar errores en el trunk a un nmero de desarrolladores/integradores.
Aun estamos analizando las ventajas de ambas herramientas.
S que el TAC est analizando la forma de hacer las revisiones de cdigo, a lo mejor Gerrit no lo ha tenido en cuenta, lo que podis hacer es comentrselo para que lo tengan en cuenta. Lo que est claro que ahora que estn en el proceso de definicin deberamos encontrar la mejor forma para hacerlo. Una vez que est definido no deberamos coger otros mtodos.

Habiendo utilizado tambin github, y sus pull request, creo que es ms fcil de usar, por ser todo mucho ms visual, pero no te permite la flexibilidad que te permite Gerrit. Aunque github tiene muchos posibles hooks a los que invocar cuando se haga un cambio, esto (que yo haya visto) no se puede hacer cuando haya una peticin de pull (puesto que no hay un cambio en el repositorio, si no en uno externo pidiendo que se integre en el "central"). Sin embargo, usando gerrit hay un montn de posibilidades y como comenta Fernando, la idea de que cuando alguien haga un push de un cambio para revisin, se pasen automticamente tests y se haga una compilacin para probar me parece mucho ms seguro y al fin y al cabo, fiable para los proyectos (por comparar, no me gustara hacer un merge de un pull en github y tener que esperar hasta aceptarlo en el repositorio oficial-central para que se pasen los tests y las revisiones automticas).

Muchas gracias,

Fernando.
Salu2
Carlos

Un saludo

De: CARLOS ENRIQUE GOMEZ GOMEZ <carlosg@tid.es<mailto:carlosg@tid.es>>
Fecha: Fri, 2 Mar 2012 14:26:17 +0100
Para: M Angeles Oteo <oteo@tid.es<mailto:oteo@tid.es>>, DANIEL JESUS COLOMA BAIGES <dcoloma@tid.es<mailto:dcoloma@tid.es>>, ANA MARIA ALARCON SANCHEZ <amas@tid.es<mailto:amas@tid.es>>, JOSE MANUEL CANTERA FONSECA <jmcf@tid.es<mailto:jmcf@tid.es>>, GUSTAVO MARTIN BOUSO <gustavom@tid.es<mailto:gustavom@tid.es>>
CC: JESUS MON RIVERA <jesusm@tid.es<mailto:jesusm@tid.es>>
Asunto: Peticiones al EPG para OWD

Hola,
   He estado hablando con el EPG, y me comenta:
-   GITHUB
  -   Se utilizar GitHub Enterprise en la nube, nos olvidamos de gittid, por tanto el problema de la gente de Mozilla desaparece
  -   Estar disponible a partir del 15 de Marzo
-   Mquina para CI
  -   La mquina fsica mxima que os puede proporcionar el EPG es una Intel core2 Quad con 4Gb de RAM

Salu2
Carlos

---

Este mensaje se dirige exclusivamente a su destinatario. Puede consultar nuestra poltica de envo y recepcin de correo electrnico en el enlace situado ms abajo.
This message is intended exclusively for its addressee. We only send and receive email on the basis of the terms set out at
http://www.tid.es/ES/PAGINAS/disclaimer.aspx
