### ISSUE TITLE
Your device has unknown firmware GINGERBREAD.DZKJ2

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#156]
$ make config-galaxy-s2
/home/arky/src/B2G/glue/gonk/out/host/linux-x86/bin/adb start-server
adb server is out of date.  killing...
- daemon started successfully *
  Extracting binary blobs from device, which should be plugged in! ...
  Your device has unknown firmware GINGERBREAD.DZKJ2
  make: **\* [config-galaxy-s2] Error 1

Device: 
Samsung SII 

Model Number: GT-I9100G 
Baseband Version: I9100GDZKJ2
Build Number: GINGERBREAD.DZKJ2

Android: 2.3.6

**Comment by jlebar** [comment]
You need to modify `glue/gonk/device/samsung/galaxys2/extract-files.sh` to be aware of your firmware.

**Comment by arky** [comment]
Thanks, I am gonna make a pull request for that. 

Next Bug in this thread:
https://github.com/andreasgal/B2G/issues/157

**Comment by arky** [comment]
Closed 

See comment for more info. 
https://github.com/andreasgal/B2G/issues/163#issuecomment-4339194
