### ISSUE TITLE
remote object '/system/lib/libfimc.so' does not exist

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#157]
$ make config-galaxy-s2
/home/arky/src/B2G/glue/gonk/out/host/linux-x86/bin/adb start-server
adb server is out of date.  killing...
- daemon started successfully *
  Extracting binary blobs from device, which should be plugged in! ...
  Pulling "libActionShot.so"
  1489 KB/s (594465 bytes in 0.389s)
  Pulling "libakm.so"
  500 KB/s (38392 bytes in 0.074s)
  Pulling "libarccamera.so"
  1937 KB/s (2578783 bytes in 1.299s)
  Pulling "libcamera_client.so"
  695 KB/s (90440 bytes in 0.126s)
  Pulling "libcameraservice.so"
  672 KB/s (59352 bytes in 0.086s)
  Pulling "libcamera.so"
  1286 KB/s (371968 bytes in 0.282s)
  Pulling "libcaps.so"
  1593 KB/s (905356 bytes in 0.554s)
  Pulling "libexif.so"
  385 KB/s (40968 bytes in 0.103s)
  Pulling "libfimc.so"
  remote object '/system/lib/libfimc.so' does not exist
  Failed to pull libfimc.so. Giving up.
  make: **\* [config-galaxy-s2] Error 255

Device:
Samsung SII

Model Number: GT-I9100G
Baseband Version: I9100GDZKJ2
Build Number: GINGERBREAD.DZKJ2

Android: 2.3.6

**Comment by jlebar** [comment]
It sounds like, on your firmware, you do not have libfimc.so.  So you should not be pulling it.

**Comment by arky** [comment]
Looks like there is already an open bug related. 

https://github.com/andreasgal/B2G/issues/138

**Comment by arky** [comment]
Lot more files are missing what's happening here

libfimc.so
libfimg.so
libMali.so
libs5pjpeg.so
libtvoutcec.so
libtvoutddc.so
libtvoutedid.so
libtvoutfimc.so

**Comment by jlebar** [comment]
Try building without all those files.  They may not be critical.

**Comment by arky** [comment]
libtvoutfimg.so
libtvouthdmi.so
Bummer ! 
libsecjpegencoder.so

**Comment by arky** [comment]
Well, I can't continue the building coz 'make config-galaxy-s2'' wont let me

**Comment by jlebar** [comment]
If you log in to IRC, we can try to help you.

**Comment by arky** [comment]
This bug is now tracked at 
https://github.com/andreasgal/B2G/issues/163
