### ISSUE TITLE
Vibrator doesn't work in galaxy S II

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#158]
Just recently I noticed that gaia uses navigator.vibrate(), but I've never felt it.  I investigated a bit on a flight, notes below

insmod /lib/modules/vibrator.ko
insmod /lib/modules/vibrator.ko
insmod: can't insert '/lib/modules/vibrator.ko': invalid module format
- the vibrator.ko that gets copied into boot/initramfs/lib/modules
  after make modules is _different_ than the one in
  boot/kernel-galaxys2 _after_ make kernel completes.
- insmod'ing the vibrator.ko built after the full compile works
  perfectly, vibrator fully functional
- mkdir initramfs && make kernel && [set up initramfs] && make kernel
  gets the right vibrator.ko into boot/initramfs/lib/modules, but
  then we get a crash cycle on rebooting :/

**Comment by joneschrisg** [comment]
CC @michaelwu @ThinkerYZu

**Comment by michaelwu** [comment]
Interesting. I never noticed this before since this only affects the first fresh build of a kernel.

**Comment by mvines** [comment]
FWIW, akami should be solid in this department.  No .ko needed:

  # echo 1000 > /sys/class/timed_output/vibrator/enable

**Comment by michaelwu** [comment]
Should've been fixed by https://github.com/andreasgal/B2G/commit/4c7a86a61e8d8f4fd34efccb1ad144da11989a30
