### ISSUE TITLE
Cyanogenmod Link Broken: Update-cm-7.1.0-GalaxyS2-signed.zip 

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#159]
Looks like extract-cm.sh cynogenmod link broken

http://download.cyanogenmod.com/get/update-cm-7.1.0-GalaxyS2-signed.zip
## snip

CM_DOWNLOAD_SITE=http://download.cyanogenmod.com/get
CM_IMAGE=update-cm-7.1.0-GalaxyS2-signed.zip
CM_ROOT=cm_root

**Comment by joneschrisg** [comment]
I'm seeing

Website Offline, No Cached Version Available

The website you are trying to access is currently offline. The most likely causes are the server is down for maintenance, there may be a network problem, or the site may be experiencing excessive load.
...

Not much we can do right now :/

**Comment by arky** [comment]
Yup! Closing this one then
