### ISSUE TITLE
some submodule urls are ssh urls

### ISSUE THREAD

**Issue by tbsaunde** [andreasgal/B2G#16]
patch coming

**Comment by MikiCAR** [comment]
When type make sync, I get:

Makefile:32: **\* Sorry, you need to set ANDROID_SDK in your environment to point at the top-level of the SDK install.  For now..  Stop.

After setting it and re-ranning make sync, I get:

fatal: Not a git repository (or any of the parent directories): .git
make: **\* [sync] Error 128

**Comment by joneschrisg** [comment]
@MikiCAR, I think you're seeing some other problem.  Please file another issue or hop on #b2g at irc.mozilla.org to chat with us.

**Comment by MikiCAR** [comment]
I have problems with IRC and  I'm in right directory like you see, I post
trace.txt and do you need something else before I go to bed.

**Comment by joneschrisg** [comment]
As we eventually discovered on IRC, the clone of this repo was severely damaged, which was causing many other things to break.
