### ISSUE TITLE
Move bionic modifications to a b2g-specific branch

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#160]
Right now they're on the gingerbread branch.  All the other repos we've forked use parallel gingerbread-b2g (or b2g-gingerbread, sorry) branches to track changes.  This allows us to merge from upstream whenever we want, and then merge to the parallel branch at our leisure, without conflicts.  It also makes it easier for us to track b2g-specific changes.

We should back out the changes to platform_bionic/gingerbread and then reland them on a b2g-gingerbread branch.

I'm about to pile on one more change for akami build support, because that's critically urgent right now.  Please let's not pile on more.

**Comment by mvines** [comment]
we could back out the akami bionic change now that system.img has been de-bloated.

**Comment by michaelwu** [comment]
No backouts or relanding necessary. I just changed where the gingerbread branch pointed to and made a new branch named b2g-gingerbread pointing to what we had on gingerbread.
