### ISSUE TITLE
GT-19100G:: Provide Support For Gingerbread.DZKJ2 firmware

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#163]
Provide build support for Samsung SII GT-19100G

Model Number: GT-I9100G
Baseband Version: I9100GDZKJ2
Build Number: GINGERBREAD.DZKJ2

**Comment by arky** [comment]
You can build B2G for this device/firmware. You will more information here:
https://github.com/andreasgal/B2G/issues/157

**Comment by arky** [comment]
More device information:
PDA: I9100GDZKJ2
Phone: I9100GDZKJ2
CSC: 19100G0LCKJ2
Build Info: Fri Oct 21 19:47:33 KST 2011

**Comment by arky** [comment]
Alright cyanogenmod does not support Samsung S2 GT-i9100G series. Can anyone confirm if they build and install B2G on this series

**Comment by shianyow** [comment]
SGS2 GT-i9100G is using different chip from generally available SGS2 GT-i9100.
The current B2G doesn't support this model yet.

**Comment by arky** [comment]
Thanks for the clarification, shianyow.
