### ISSUE TITLE
Install |perf| onto device

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#167]
See https://bugzilla.mozilla.org/show_bug.cgi?id=720467#c44 .

I feel a bit uneasy about taking a tool like this of unknown provenance (to me).  Would be happier if we had our own build.  But the benefit might outweigh the cost if it's not easy to build.

**Comment by andreasgal** [comment]
Can do it temporarily until we build it.

**Comment by jlebar** [comment]
We already build a kernel, so I can't imagine it's _so_ hard to build perf.  But I agree with Andreas: We probably have better things to do atm.

**Comment by vicamo** [comment]
is this a duplicated issue of [#23](https://github.com/andreasgal/B2G/issues/23)?

**Comment by joneschrisg** [comment]
#23 can cover porting the source (or whatever else we need to do) to actually build |perf|.  This issue can cover installing a pre-built binary so we can start using |perf| as soon as possible.

**Comment by shianyow** [comment]
It was integrated to b2g.

Below are some simple ways to use it.
Remember to replace libxul.so or other libraries with symbols.
1. See real time performance
   perf top -p "pid of b2g"
2. Record and report with summary (do this in a writable directory)
   perf record -p "pid of b2g"
   perf report > perf_report.txt
3. Record and report with callgraph
   perf record -g -p "pid of b2g"
   perf report > perf_report.txt

use "c++filt" at host side to handle C++ demanging in reports.

Sometimes devices may crash when doing perf with callgraph, especially when CSS animation with battery is enabled.
This is an issue to be fixed.

**Comment by joneschrisg** [comment]
So awesome, thanks @shianyow.  We need to pull these instructions together somewhere.  I'll get that started after finishing up a couple of other projects.

**Comment by shianyow** [comment]
A wiki has been created at https://wiki.mozilla.org/B2G/Profiling

**Comment by joneschrisg** [comment]
\o/
