### ISSUE TITLE
Final call state on receiver's phone is 'disconnecting', not 'disconnected'

### ISSUE THREAD

**Issue by jonallengriffin** [andreasgal/B2G#178]
If you start two emulators and have one call the other, then have the receiver answer the call and then hang up, the call on the caller's phone correctly proceeds to the 'disconnected' state, but the receiver's call only proceeds to 'disconnecting' and never reaches 'disconnected'.  This is reflected in the UI by the dialer app never returning to the main screen (the red 'hang up' button is forever displayed).

There is a new Marionette test which exposes this problem, https://github.com/jonallengriffin/marionette_client/blob/master/marionette/tests/emulator/test_dial_listeners.py.

It currently fails at line 144 with a timeout, waiting for the call state on the receiver's emulator to reach 'disconnected'.

@malini

**Comment by philikon** [comment]
I wonder if this is related to https://bugzilla.mozilla.org/show_bug.cgi?id=729503.

**Comment by jonallengriffin** [comment]
> I wonder if this is related to https://bugzilla.mozilla.org/show_bug.cgi?id=729503.

Maybe, but in this case we are calling answer() and waiting for the call state to reach 'connected' before calling hangUp().

**Comment by jonallengriffin** [comment]
This problem had disappeared for a couple of weeks, but has resurfaced with http://github.com/andreasgal/B2G/commit/c86c236be82d82d9e4d9ac70f308e3121b1081ed

**Comment by philikon** [comment]
Can you turn DEBUG = true on in dom/system/gonk/{ril_worker, RadioInterfaceLayer}.js and post an adb logcat please?

**Comment by jonallengriffin** [comment]
Here's the log:  http://people.mozilla.org/~jgriffin/adb.log

**Comment by jonallengriffin** [comment]
This is passing again on the emulator, so I don't know if it's an intermittent issue, or ... ?

**Comment by philikon** [comment]
The log looks race-y. It seems the DOM and the RIL are racing each other to update the call state.

**Comment by hsinyi** [comment]
I filed a bug on Bugzilla. Please visit https://bugzilla.mozilla.org/show_bug.cgi?id=737793 for discussion. Thanks!

**Comment by jonallengriffin** [comment]
Bug 737793 has been fixed, and I haven't observed this in test results recently.
