### ISSUE TITLE
extract-files.sh should also extract /system/etc/wifi/nvram_net.text_murata

### ISSUE THREAD

**Issue by jammink** [andreasgal/B2G#179]
I had to do a few more manual hacks to get my ethernet/wifi working on my samsung galaxy s2 with my current firmware version.

flash to android
adb pull /system/etc/wifi/nvram_net.txt_murata

restore b2g again
replace the file
adb push nvram_net.txt_murata /system/etc/wifi/nvram_net.txt_murata

adb reboot

after configuring wifi in wpa_supplicant.conf wifi worked.

**Comment by jammink** [comment]
So, for the record, my firmware is:

GINGERBREAD.XWKI4

**Comment by michaelwu** [comment]
Fix pushed
