### ISSUE TITLE
gps not working on galaxy s2

### ISSUE THREAD

**Issue by davidflanagan** [andreasgal/B2G#185]
When I try to use navigator.geolocation in a gaia app, I see these lines in adb logcat:

E/gps-wrapper( 2614): load: module=/system/lib/hw/vendor-gps.smdkv310.so
E/gps-wrapper( 2614): Cannot load library: load_library[1105]: Library '/system/lib/hw/vendor-gps.smdkv310.so' not found

But when I adb shell into my device, I see that there is a /system/lib/hw/gps.smdkv310.so file, without the "vendor-" prefix in it.

The file glue/gonk/device/samsung/c1-common/gpswrapper/gps.c hardcodes that filename with the "vendor-" prefix, so I'm hoping  that removing the prefix will fix the gps issue.

I'm building to test that now, and will add a note here if it works.

**Comment by davidflanagan** [comment]
Changing the filename in gps.c to remove "vendor-" did not fix the problem.

If anything, it made it worse.  Now when I call navigator.geolocation.getCurrentPosition() the app that does it closes right away and the phone goes back to the homescreen.  At the same time adb logcat spews a lot of stuff, mostlly about wifi. I'm guessing that accessing the gps module crashes the app or something.

**Comment by joneschrisg** [comment]
This probably something wrong with gecko, but we can investigate here.  Let's talk to Kan-Ru.

**Comment by kanru** [comment]
gps.smdkv310.so is a wrapper on top of the actual gps driver. On my phone it's gps.s5pc210.so

**Comment by kanru** [comment]
I'll take this.

**Comment by kanru** [comment]
Should be fixed after reconfigure & make gonk.
