### ISSUE TITLE
Unable to connect localhost:7777

### ISSUE THREAD

**Issue by timdream** [andreasgal/B2G#187]
With latest build of b2g on galaxy s2. Homescreen won't start up.

Did I do anything wrong?

**Comment by andreasgal** [comment]
What device?

**Comment by andreasgal** [comment]
Oh galaxy s2 never mind. Please take a look at your init.rc and make sure it contains "mongoose". If not, I forgot to patch one of the many copies of init.rc we have in the tree.

**Comment by andreasgal** [comment]
Did you exchange gecko only or the entire flash?

**Comment by timdream** [comment]
I did the entire flash

**Comment by timdream** [comment]
Let's close this bug. Been told this is fixed by @michaelwu in the morning.
