### ISSUE TITLE
bionic's raise() implementation is incorrect in multithreaded program

### ISSUE THREAD

**Issue by cervantesyu** [andreasgal/B2G#189]
The raise() impl. in the bionic library we use is always progress-directed. For a multithreaded program (like b2g), the signal raised by a thread could be delivered to another thread. That might cause strange behavior: you get assertion failure, but in gdb you don't see MOZ_Assert() in the thread that receives the signal and have to print the stacks of all threads to look for the one that calls raise().

The latest raise.c in AOSP is even worse: it's half-fixed. It matches gettid() with kill(). The change to fix the issue:
diff --git a/libc/unistd/raise.c b/libc/unistd/raise.c
index de099da..7b51ea2 100644
--- a/libc/unistd/raise.c
+++ b/libc/unistd/raise.c
@@ -30,5 +30,5 @@

 int raise(int signum)
 {
-    return kill(getpid(), signum);
-    return tkill(gettid(), signum);
  }

**Comment by cervantesyu** [comment]
typo: it's process-directed, not progress-directed

**Comment by andreasgal** [comment]
sounds good. can you do a pull request?

**Comment by cervantesyu** [comment]
pull request sent: https://github.com/mozilla-b2g/platform_bionic/pull/2

**Comment by jprosevear** [comment]
Can this issue be closed?  Also https://bugzilla.mozilla.org/show_bug.cgi?id=730229 is tied to this.

**Comment by cervantesyu** [comment]
Close the issue since https://bugzilla.mozilla.org/show_bug.cgi?id=741272 avoids this problem
