### ISSUE TITLE
$ make flash-only doesn't work

### ISSUE THREAD

**Issue by jammink** [andreasgal/B2G#194]
make: **\* No rule to make target `flash-only-', needed by`flash-only'.  Stop.

**Comment by jlebar** [comment]
Some variable is missing from your Makefile.  It should be flash-only-$(something).  Maybe you need to configure?

**Comment by shianyow** [comment]
There should be something like this in ".config.mk" after configuration.

```
KERNEL = galaxy-s2
KERNEL_PATH = ./boot/kernel-android-galaxy-s2
GONK = galaxys2
```

**Comment by jammink** [comment]
Ok, this is my bad.

Right before running make flash-only, I ran the git - repo - cleaning command:

$ make sync; git clean -xfd; git submodule foreach "git clean -xfd"

which blew away my config.mk

I am sure I have to run first make-config-galaxy - s2 before running make flash-only

closing this now.
