### ISSUE TITLE
Emulator fails to start since commit 611331e3e7

### ISSUE THREAD

**Issue by jonallengriffin** [andreasgal/B2G#199]
Since commit 611331e3e73cd36e072ca4362defc4f3a7be3206, the emulator fails to start successfully.  On startup, a dialog appears with "Fatal error during startup: [No homescreen found]".

**Comment by vingtetun** [comment]
On 29/02/2012 02:24, Jonathan Griffin wrote:

> Since commit 611331e3e73cd36e072ca4362defc4f3a7be3206, the emulator fails to start successfully.  On startup, a dialog appears with "Fatal error during startup: [No homescreen found]".

There is no Gaia by default on the device anymore. You should install it 
after the compilation with |make install-gaia|.

**Comment by joneschrisg** [comment]
(As a workaround.  We'll be fixing this properly soon.)

**Comment by jonallengriffin** [comment]
Apparently, the emulator is out of memory, so 'make install-gaia' fails.  Increasing the memory in emu.sh from 512 to 2048 fixes this and allows gaia to launch.

**Comment by jonallengriffin** [comment]
So, it turns out we don't need |make install-gaia| with the emulator.  What we do need is to add -partition-size 512 to the emulator command-line (discovered by @malini), to prevent the /data dir from running out of space during startup.  On a clean, mrproper build, launching the emulator with this extra arg allows it to start successfully without doing |make install-gaia|.  

We don't need to increase the memory above 512.

For running multi-emulator tests, emulators after the first notice that userdata.img is already in use and make a temporary copy of it for the second emulator, but -partition-size doesn't seem to get applied to the copy, and the result is the "Fatal error during startup..." message.  Specifying an explicit copy of userdata.img for the second emulator instance fixes this problem.  I'll update Marionette to do that.

I'll submit a pull request to add -partition-size to emu.sh.
