### ISSUE TITLE
Homescreen loads fine but no Internet connection in emulator

### ISSUE THREAD

**Issue by robhawkes** [andreasgal/B2G#201]
I finally managed to get B2G to build in Ubunutu after a bit of trial and error. I can now load it up via the emulator and everything seems to load ok; the lock screen appears, apps show up and I can click stuff. Unfortunately there doesn't seem to be an Internet connection so none of the apps can connect to anything.

I didn't see any instructions for setting up the Internet for the emulator version of B2G. Is there something specific that I need to do to get it working?

If it helps, here is the log of my call to emu.sh to load up the emulator: http://pastebin.com/93BsL6mi

Hoping we can work this out.

Rob

**Comment by joneschrisg** [comment]
@robhawkes the output from |adb logcat| would be very useful in helping us diagnose this.

CC @mrbkap @philikon @malini @jonallengriffin

**Comment by robhawkes** [comment]
Thanks Chris, here is the |adb logcat| output, looks like there is a specific bit about WiFi at the end: http://pastebin.com/TQ8N3Uby

**Comment by jonallengriffin** [comment]
This is the same out-of-memory problem I noted in issue 199.  To fix it, just edit emu.sh to replace '512' with '4096' for the -memory argument.

Chris, what should we be using for the memory arg these days?

**Comment by jonallengriffin** [comment]
Err, never mind, increasing the memory doesn't seem to fix this.

**Comment by robhawkes** [comment]
Thought I'd give it a shot anyway but I can confirm that it didn't fix the issue. Thanks though!

**Comment by mrbkap** [comment]
From the logcat, I see:
  I/Gecko   (   34): WIFI: load_driver returned: -1

This means that the emulator wasn't able to load the wifi driver. Is there any output in dmesg that looks like it might be related?

**Comment by robhawkes** [comment]
Looking this with a fresh pair of eyes I might see the obvious problem here. I'm using Ubuntu on VM Ware which is sharing an Internet connection with my Mac which is in turn made to look like an ethernet connection. Therefore there isn't a wireless adapter installed on the Ubuntu VM which would explain the driver not being found.

I assume the emulator doesn't fake a wireless Internet connection even if there is only ethernet on the computer?

**Comment by robhawkes** [comment]
I can't seem to replecate a wireless connection in VM Ware so I might be out of luck here.

**Comment by joneschrisg** [comment]
The emulator should have virtual NIC devices that use whatever the default host NIC is.  That's how the emulator can expose 3g data connections, e.g.  I don't know with 100% certainty that there's a virtual WNIC device but there should be.  We'll investigate this next week.

**Comment by robhawkes** [comment]
Thanks Chris, I'll be interested to hear how the investigation goes. I'll update here if I manage to figure it out myself.

**Comment by michaelwu** [comment]
I fixed this. https://github.com/cgjones/android-system-core/commit/7013485da737088c3ef718e025d76cc5364a5d38
