### ISSUE TITLE
Phone continues to ring - through ear speaker - while phone is on call

### ISSUE THREAD

**Issue by jammink** [andreasgal/B2G#206]
Latest pull (gonk/gecko/gaia) 3/5

Curiously enough, just after I'd pulled and built today, I got a call from a telemarketer =) to my test phone.  The phone continued to ring  - through the ear speaker - during the call.

Reproduced it and caught logcat: http://pastebin.mozilla.org/1504277

**Comment by philikon** [comment]
This is a gaia issue. Please file it there.

**Comment by jammink** [comment]
Possibly related to https://bugzilla.mozilla.org/show_bug.cgi?id=723372 ?

**Comment by philikon** [comment]
No. Gecko doesn't provide the ring tone. Gaia does.

**Comment by vingtetun** [comment]
On 06/03/2012 03:50, John Hammink wrote:

> Latest pull (gonk/gecko/gaia) 3/5
> 
> Curiously enough, just after I'd pulled and built today, I got a call from a telemarketer =) to my test phone.  The phone continued to ring  - through the ear speaker - during the call.
> 
> Reproduced it and caught logcat: http://pastebin.mozilla.org/1504277

Sounds like a Gaia issue.

@etiennesegonzac can you look at that?

**Comment by etiennesegonzac** [comment]
Will do!

**Comment by jammink** [comment]
I just tested this with the latest gaia pull (3/6).  It appears the problem is fixed.
