### ISSUE TITLE
B2G App Fails to Start

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#210]
$ b2g=declare -x B2G_HOMESCREEN=http://gaiamobile.org:8888/apps/homescreen/homescreen.html && /home/arky/src/b2g-build/dist/bin/b2g -P b2g

======================= webapi+apps.js ======================= 
### !!! ABORT: Request 139.66: BadRequest (invalid request code or no such operation): file /home/arky/src/mozilla-central/toolkit/xre/nsX11ErrorHandler.cpp, line 190

Segmentation fault (core dumped)

$ cat .mozconfig
mk_add_options MOZ_OBJDIR=../b2g-build
mk_add_options MOZ_MAKE_FLAGS="-j8 -s"
ac_add_options --enable-application=b2g
ac_add_options --disable-libjpeg-turbo
ac_add_options --with-ccache=/usr/bin/ccache

**Comment by fzzzy** [comment]
The link http://gaiamobile.org:8888/apps/homescreen/homescreen.html doesn't load for me with firefox or curl, so that's probably the problem. Try using a file:// url instead.

**Comment by arky** [comment]
I will try that. 

Build another one with debug flags. Here is what I get from GDB. 

(gdb) run
Starting program: /home/arky/src/obj-i686-pc-linux-gnu-debug/dist/bin/b2g 
[Thread debugging using libthread_db enabled]

X Error of failed request:  BadRequest (invalid request code or no such operation)
  Major opcode of failed request:  139 (ATIFGLEXTENSION)
  Minor opcode of failed request:  66 ()
  Serial number of failed request:  14
  Current serial number in output stream:  14
nsStringStats
 => mAllocCount:              1
 => mReallocCount:            0
 => mFreeCount:               0  --  LEAKED 1 !!!
 => mShareCount:              0
 => mAdoptCount:              0
 => mAdoptFreeCount:          0
[New Thread 0xb78ffb70 (LWP 13329)]
[New Thread 0xb70feb70 (LWP 13330)]
[New Thread 0xb68fdb70 (LWP 13331)]
[New Thread 0xb60fcb70 (LWP 13332)]
[New Thread 0xb56ffb70 (LWP 13333)]
[New Thread 0xb47ffb70 (LWP 13334)]
[New Thread 0xb3ffeb70 (LWP 13335)]
[New Thread 0xb37fdb70 (LWP 13336)]
[New Thread 0xb2edab70 (LWP 13337)]
WARNING: GetDefaultCharsetForLocale: need to add multi locale support: file /home/arky/src/mozilla-central/intl/locale/src/unix/nsUNIXCharset.cpp, line 150
WARNING: 1 sort operation has occurred for the SQL statement '0xb25bb540'.  See https://developer.mozilla.org/En/Storage/Warnings details.: file /home/arky/src/mozilla-central/storage/src/mozStoragePrivateHelpers.cpp, line 144
++DOCSHELL 0xb2334800 == 1
pldhash: for the table at address 0xb22044f0, the given entrySize of 48 probably favors chaining over double hashing.
[New Thread 0xacdf8b70 (LWP 13338)]
++DOCSHELL 0xb2334e00 == 2
++DOMWINDOW == 1 (0xb7db6428) [serial = 1] [outer = (nil)]
++DOMWINDOW == 2 (0xb7db65c8) [serial = 2] [outer = 0xb7db63e0]
[New Thread 0xac122b70 (LWP 13339)]
++DOMWINDOW == 3 (0xb7db7608) [serial = 3] [outer = (nil)]
++DOMWINDOW == 4 (0xb7db77a8) [serial = 4] [outer = 0xb7db75c0]
++DOCSHELL 0xb2336e00 == 3
++DOMWINDOW == 5 (0xb7d5d808) [serial = 5] [outer = (nil)]
++DOMWINDOW == 6 (0xb7d5e618) [serial = 6] [outer = 0xb7d5d7c0]
++DOMWINDOW == 7 (0xb7d5e7a8) [serial = 7] [outer = 0xb7d5d7c0]
++DOCSHELL 0xb2339a00 == 4
++DOMWINDOW == 8 (0xb7db8648) [serial = 8] [outer = (nil)]
++DOMWINDOW == 9 (0xb7db87e8) [serial = 9] [outer = 0xb7db8600]
[New Thread 0xa74feb70 (LWP 13340)]
###!!! ABORT: Request 139.66: BadRequest (invalid request code or no such operation); id=0x5200153
Re-running with MOZ_X_SYNC=1 in the environment may give a more helpful backtrace.: file /home/arky/src/mozilla-central/toolkit/xre/nsX11ErrorHandler.cpp, line 190
UNKNOWN [/home/arky/src/obj-i686-pc-linux-gnu-debug/dist/bin/libxul.so +0x003F03F4]
UNKNOWN [/usr/lib/libbonoboui-2.so.0 +0x0001EA75]
###!!! ABORT: Request 139.66: BadRequest (invalid request code or no such operation); id=0x5200153
Re-running with MOZ_X_SYNC=1 in the environment may give a more helpful backtrace.: file /home/arky/src/mozilla-central/toolkit/xre/nsX11ErrorHandler.cpp, line 190

Program received signal SIGSEGV, Segmentation fault.
0x00459054 in TouchBadMemory ()
    at /home/arky/src/mozilla-central/memory/mozalloc/mozalloc_abort.cpp:66
warning: Source file is more recent than executable.
66      // XXX this should use the frame poisoning code

**Comment by arky** [comment]
Please help !
@fzzzy  @cgjones @andreasgal 

$ declare -x B2G_HOMESCREEN=file://home/arky/src/gaia/homescreen.html 
$ src/b2g-build/dist/bin/b2g 
Cannot open socket for RIL!
-_\- nsWifiWorker component: Wifi starting
SmsDatabaseService: Opened database: sms 1
Could not load libcutils.so. Using fake propdb.
Could not load libnetutils.so!
-_\- nsWifiWorker component: Got an error from the control worker: resource://gre/modules/libhardware_legacy.js:7: couldn't open library

-*- nsWifiWorker component: Got an error from the event worker: resource://gre/modules/libhardware_legacy.js:7: couldn't open library

Cannot open socket for RIL!
###!!! ABORT: Request 139.66: BadRequest (invalid request code or no such operation): file /home/arky/src/mozilla-central/toolkit/xre/nsX11ErrorHandler.cpp, line 190
###!!! ABORT: Request 139.66: BadRequest (invalid request code or no such operation): file /home/arky/src/mozilla-central/toolkit/xre/nsX11ErrorHandler.cpp, line 190
Segmentation fault (core dumped)

**Comment by fzzzy** [comment]
file:/// urls have three slashes at the beginning... the first two indicate the file protocol, and the last one is the first slash in a path.

Try: file:///home/arky/src/gaia/homescreen.html

**Comment by arky** [comment]
Thanks @fzzzy 

Presto! That's it. Can't believe how _stupid_ that was.

**Comment by arky** [comment]
@fzzzy  Addendum:

Using '-safe-mode' argument helps me launch b2g app.  

```
#!/bin/sh 

export B2G_HOMESCREEN=file:///home/arky/src/gaia/homescreen.html 
/home/arky/src/b2g-build/dist/bin/b2g -safe-mode
```

Otherwise my b2g app fails with .... 

Cannot open socket for RIL!
-_\- nsWifiWorker component: Wifi starting
SmsDatabaseService: Opened database: sms 1
Could not load libcutils.so. Using fake propdb.
Could not load libnetutils.so!
-_\- nsWifiWorker component: Got an error from the control worker: resource://gre/modules/libhardware_legacy.js:7: couldn't open library

-*- nsWifiWorker component: Got an error from the event worker: resource://gre/modules/libhardware_legacy.js:7: couldn't open library

======================= webapi+apps.js ======================= 
Cannot open socket for RIL!
Cannot open socket for RIL!
Cannot open socket for RIL!
Cannot open socket for RIL!
###!!! ABORT: Request 139.66: BadRequest (invalid request code or no such operation): file /home/arky/src/mozilla-central/toolkit/xre/nsX11ErrorHandler.cpp, line 190
###!!! ABORT: Request 139.66: BadRequest (invalid request code or no such operation): file /home/arky/src/mozilla-central/toolkit/xre/nsX11ErrorHandler.cpp, line 190
Segmentation fault (core dumped)
arky@Arky-Think:~$ bin/b2g
Cannot open socket for RIL!
-_\- nsWifiWorker component: Wifi starting
SmsDatabaseService: Opened database: sms 1
Could not load libcutils.so. Using fake propdb.
Could not load libnetutils.so!
-_\- nsWifiWorker component: Got an error from the control worker: resource://gre/modules/libhardware_legacy.js:7: couldn't open library

-*- nsWifiWorker component: Got an error from the event worker: resource://gre/modules/libhardware_legacy.js:7: couldn't open library

======================= webapi+apps.js ======================= 
Cannot open socket for RIL!
Cannot open socket for RIL!
Cannot open socket for RIL!
Cannot open socket for RIL!
###!!! ABORT: Request 139.66: BadRequest (invalid request code or no such operation): file /home/arky/src/mozilla-central/toolkit/xre/nsX11ErrorHandler.cpp, line 190
###!!! ABORT: Request 139.66: BadRequest (invalid request code or no such operation): file /home/arky/src/mozilla-central/toolkit/xre/nsX11ErrorHandler.cpp, line 190
Segmentation fault (core dumped)
