### ISSUE TITLE
Gaia checkbox state low contrast

### ISSUE THREAD

**Issue by hfiguiere** [andreasgal/B2G#218]
The Gaia checkbox state is too low contrast and might be unusable in case of color blindness. Currently the checkmark is always in the box, green for checked and gray for unchecked. I do believe that when uncheched the check box should be empty.

**Comment by vingtetun** [comment]
This is a Gaia issue. I've opend bug https://github.com/andreasgal/gaia/issues/808 for that.
Thanks for reporting.
