### ISSUE TITLE
Default mozconfig shouldn't include --with-ccache

### ISSUE THREAD

**Issue by mounirlamouri** [andreasgal/B2G#234]
That makes build fails if ccache isn't installed and there is any reason why ccache should be pushed more for b2g than any other Mozilla build (like Firefox or Thunderbird).

BTW, why using a default mozconfig instead of putting default values in configure.in?

**Comment by andreasgal** [comment]
ccache is an easy dependency and it makes builds a million times faster. why would we not use it?

**Comment by joneschrisg** [comment]
The android build also relies on it.  It's silly not to use it.

The options in the b2g mozconfig aren't suitable for upstream default yet.

**Comment by mounirlamouri** [comment]
I've been using ccache on my laptop for a long time and my conclusion is that ccache is probably not that useful. ccache probably helps you a lot when you have a lot of hits but doesn't help that much if the repo has changed a lot. Also, ccache might significantly reduce performances in some situations because it's doing a lot of I/O, especially when there are a lot of miss.
Nowadays, I don't use ccache anymore and even less on my desktop which compiles gecko in about 10 minutes.

Anyway, ccache is a tool and I don't think my compilation should fail just because I don't have it installed. I wouldn't complain if ccache was automatically used if present but I think it should not be used if not present instead of stopping the compilation.

**Comment by jlebar** [comment]
Unlike with vanilla Gecko, few people modify their b2g mozconfigs.  So the defaults are important.

Three of us now in this thread like ccache, and you're the only one who doesn't.  So can we just resolve this by your taking out ccache of your mozconfig?

**Comment by mounirlamouri** [comment]
I've no influence in b2g code and this repo. I've just opened a bug because I believe it's an issue and I'm trying to defend my point of view. If the conclusion is that more people benefits from that than suffers, I'm not going to fight and I've already changed the mozconfig in my clone.

**Comment by andreasgal** [comment]
This really isn't a big deal. We have bigger fish to try.
