### ISSUE TITLE
Samsung S2 1900 make fails with..

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#238]
$ make config-galaxy-s2 
.....
Resolving raw.github.com... 207.97.227.243
Connecting to raw.github.com|207.97.227.243|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 180896 (177K) [text/plain]
Saving to: `/home/arky/src/B2G/glue/gonk/vendor/apns-conf.xml'

100%[======================================>] 180,896      274K/s   in 0.6s    

2012-03-24 18:14:47 (274 KB/s) - `/home/arky/src/B2G/glue/gonk/vendor/apns-conf.xml' saved [180896/180896]

Extracting binary blobs from device, which should be plugged in! ...
Your device has unknown firmware GINGERBREAD.DXKG3

**Comment by fabricedesre** [comment]
You need to update glue/gonkdevice/samsung/galaxys2/extract-files.sh to add support for this firmware version

**Comment by arky** [comment]
@fabricedesre Patched the file and issued a pull request 

https://github.com/arky/android_device_samsung_galaxys2/tree/patch-1
