### ISSUE TITLE
emulator build broken: 'ALOGW' was not declared in this scope

### ISSUE THREAD

**Issue by jonallengriffin** [andreasgal/B2G#243]
...followed by lots of other similar errors for other undeclared macros/constants.

See full log:  http://ec2-107-20-108-245.compute-1.amazonaws.com/jenkins/job/b2g-build/171/console

**Comment by joneschrisg** [comment]
This is "the" GB build bustage.  Fix going through upstream now, should be merged in soon.

**Comment by jonallengriffin** [comment]
This is fixed now.
