### ISSUE TITLE
IDC files for akami due new ICS based input reader

### ISSUE THREAD

**Issue by jaoo** [andreasgal/B2G#254]
Just flashed a fresh build (f23375551e4c7f1f1f50c666232ee7981251d7bc) and It seems everything is fine but the screen/UX does not react to any touch event.  We need to put in idc files for akami as @michaelwu suggested. They're stored in /system/usr/idc on the device and might be some standard copies around somewhere.

**Comment by andreasgal** [comment]
Want to do a pull request or should we get someone from our side on this?

**Comment by jaoo** [comment]
If you think it blocks any work in progress or simply that it has to be solved solved ASAP please free to get someone on your side. If not I would like to take a look and work on it during this weekend.

**Comment by mvines** [comment]
Might need to back out https://bugzilla.mozilla.org/show_bug.cgi?id=739417 as well for maguro/akami.  I did.

**Comment by andreasgal** [comment]
mvines, want to add a quick patch on top of 739417 that detects sgs2 based on boardconfig prop and only does that hack there?

**Comment by andreasgal** [comment]
mvines is afk for a while, need an owner here, mwu is probably good

**Comment by andreasgal** [comment]
@faramarzr can you please drive this?

**Comment by michaelwu** [comment]
I have a patch that just needs to be tested.

**Comment by michaelwu** [comment]
Part of the fix has been committed. The other half is in https://bugzilla.mozilla.org/show_bug.cgi?id=741038

**Comment by michaelwu** [comment]
Well, this issue was just for the idc files anyway, so I'm closing it. The remaining work will be tracked on bugzilla.
