### ISSUE TITLE
emulator unresponsive after restart

### ISSUE THREAD

**Issue by jonallengriffin** [andreasgal/B2G#255]
After a clean build, the emulator starts successfully.  However, after shutting down and restarting the emulator, the screen is unresponsive.  The lock screen does not show the time and cannot be unlocked.

Logcat:

D/EventHub(   34): No input device configuration file found for device 'qwerty2'.
E/Keyboard(   34): Could not determine key map for device 'qwerty2' and no default key maps were found!
I/EventHub(   34): New device: id=1, fd=37, path='/dev/input/event0', name='qwerty2', classes=0x8d, configuration='', keyLayout='', keyCharacterMap='', builtinKeyboard=false
E/EventHub(   34): could not get driver version for /dev/input/mouse0, Not a typewriter
E/EventHub(   34): could not get driver version for /dev/input/mice, Not a typewriter
I/InputReader(   34): Device reconfigured: id=1, name='qwerty2', surface size is now 480x856, mode is 2
I/InputReader(   34): Device added: id=1, name='qwerty2', sources=0x80100109
E/GeckoConsole(   34): Attempt to use JS function on a different thread calling nsIDirectoryServiceProvider.getFile. JS objects may not be shared across threads.
I/Gecko   (   34): SmsDatabaseService: Could not open database: Error opening database!
I/GeckoDump(   34): Opened socket on 9999
E/GeckoConsole(   34): [JavaScript Error: "The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must to be declared in the document or in the transfer protocol." {file: "data:text/html,%3C!DOCTYPE%20html>%3Cbody%20style='background:black;'>" line: 0}]
I/ServiceManager(   36): (B2G) Returning fake true permission: android.permission.MODIFY_AUDIO_SETTINGS from uid=0 pid=34
I/ServiceManager(   36): (B2G) Returning fake true permission: android.permission.MODIFY_AUDIO_SETTINGS from uid=0 pid=34
I/GeckoDump(   34): XxXxX adding permissions for http://browser.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://calculator.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://contacts.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://camera.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://clock.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://crystalskull.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://cubevid.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://dialer.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://gallery.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://homescreen.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://maps.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://market.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://music.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://penguinpop.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://settings.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://sms.gaiamobile.org
I/Gecko   (   34): RIL Worker: DateTimeZone string 12/03/30:19:47:16-28:1:America!Los_Angeles
I/GeckoDump(   34): XxXxX adding permissions for http://towerjelly.gaiamobile.org
I/GeckoDump(   34): XxXxX adding permissions for http://video.gaiamobile.org
I/Gecko   (   34): ======================= webapi+apps.js ======================= 
I/Gecko   (   34): WIFI: load_driver returned: -1
I/Gecko   (   34): -_\- WifiWorker component: Couldn't start Wifi
I/Gecko   (   34): *_\* AUS:SVC Checker:getUpdateURL - update URL: http://update.boot2gecko.org/m2.5/updates.xml
E/GeckoConsole(   34): AUS:SVC Checker:getUpdateURL - update URL: http://update.boot2gecko.org/m2.5/updates.xml
I/Gecko   (   34): **\* AUS:SVC gCanCheckForUpdates - able to check for updates
E/GeckoConsole(   34): AUS:SVC gCanCheckForUpdates - able to check for updates
I/Gecko   (   34): **\* AUS:SVC Checker:checkForUpdates - sending request to: http://update.boot2gecko.org/m2.5/updates.xml
E/GeckoConsole(   34): AUS:SVC Checker:checkForUpdates - sending request to: http://update.boot2gecko.org/m2.5/updates.xml
I/Gecko   (   34): **\* UTM:SVC TimerManager:notify - notified @mozilla.org/updates/update-service;1
E/GeckoConsole(   34): UTM:SVC TimerManager:notify - notified @mozilla.org/updates/update-service;1
E/GeckoConsole(   34): [JavaScript Error: "syntax error" {file: "http://update.boot2gecko.org/m2.5/updates.xml" line: 1 column: 50 source: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">"}]
I/Gecko   (   34): **\* AUS:SVC Checker:onProgress - 301/301
E/GeckoConsole(   34): AUS:SVC Checker:onProgress - 301/301
I/Gecko   (   34): **\* AUS:SVC Checker:onLoad - request completed downloading document
E/GeckoConsole(   34): AUS:SVC Checker:onLoad - request completed downloading document
I/Gecko   (   34): **\* AUS:SVC Checker:updates get - unexpected node name!
E/GeckoConsole(   34): AUS:SVC Checker:updates get - unexpected node name!
I/Gecko   (   34): **\* AUS:SVC Checker:onLoad - there was a problem checking for updates. Exception: Error: Unexpected node name, expected: updates, got: parsererror
E/GeckoConsole(   34): AUS:SVC Checker:onLoad - there was a problem checking for updates. Exception: Error: Unexpected node name, expected: updates, got: parsererror
I/Gecko   (   34): **\* AUS:SVC Checker:onLoad - request.status: 404
E/GeckoConsole(   34): AUS:SVC Checker:onLoad - request.status: 404
I/Gecko   (   34): **\* AUS:SVC getStatusTextFromCode - transfer error: Update XML file not found (404), code: 404
E/GeckoConsole(   34): AUS:SVC getStatusTextFromCode - transfer error: Update XML file not found (404), code: 404
I/Gecko   (   34): **\* AUS:SVC UpdateService:notify:listener - error during background update: Update XML file not found (404)
E/GeckoConsole(   34): AUS:SVC UpdateService:notify:listener - error during background update: Update XML file not found (404)

**Comment by michaelwu** [comment]
This was broken by the new inputreader. We're going to add an ICS based emulator which shouldn't have this issue.

**Comment by joneschrisg** [comment]
The lockscreen not showing time is something that @andreasgal has observed and thinks is a race condition in the gaia code.  I think there's an issue on file for that.

**Comment by hongyu918** [comment]
same problem,  almost same log.

**Comment by hongyu918** [comment]
The time will show after a while waiting and click on the home menu,  but still can`t be unlock.

**Comment by Zepheus** [comment]
I've also noticed this behaviour on a port I've done myself from the gingerbread sources to HTC Bravo (so not the emulator).
GDB reports: ioctl code 0x40040921 (IOCTL_KGSL_SHAREDMEM_FREE)

**Comment by jonallengriffin** [comment]
This is working now.
