### ISSUE TITLE
Problem with the b2g emulator

### ISSUE THREAD

**Issue by johnstone** [andreasgal/B2G#258]
I just build b2g code successfully (according to https://developer.mozilla.org/en/Mozilla/Boot_to_Gecko/Building_B2G_for_QEMU_Emulator) 

but after I launch the emulator ( execute ./emu.sh )

the screen of the emulator is just stay at the same as the first pic in http://blog.varunkumar.me/2012/03/screenshots-mozillas-mobile-os.html

with the text above the screen show {{connecting}} ( while in that website is show Android )

and I can't do anything with the emulator

can anyone tell me what the problem is?

**Comment by shianyow** [comment]
This is related to issue #255, which will be solved after ICS based emulator supported.
