### ISSUE TITLE
Update glue/gonk/external/qemu

### ISSUE THREAD

**Issue by jonallengriffin** [andreasgal/B2G#260]
Currently, glue/gonk/external/qemu points to the tools_r13 branch of that repo.  However, there's a change in the master branch which we need in order to be able to test vibrator and other API's in the emulator; that change is https://github.com/cgjones/android-external-qemu/commit/2d88523d26c66692cdb3019e5b1bf252066eb32b.

Can we update glue/gonk/external/qemu to point to this commit?

**Comment by joneschrisg** [comment]
Have you confirmed that our testing code works fine with the version of the code on the master branch?

CC @shianyow

**Comment by jonallengriffin** [comment]
@cgjones @shianyow  yes, all of the tests that pass with the current branch also pass with the master branch

**Comment by joneschrisg** [comment]
8e8dacd826497ced2739cfdeff146b3f0f8c6d10
