### ISSUE TITLE
Nexus S ICS build is broken

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#264]
I had accidentally switched to nexus-s GB, switching back to ICS got me:

awk: cmd. line:1: fatal: cannot open file `sdk/files/tools_source.properties' for reading (No such file or directory)
find:`../../external/nist-sip/java': No such file or directory
No private recovery resources for TARGET_DEVICE crespo
make[1]: Entering directory `/home/cjones/mozilla/b2g/glue/gonk-ics'
host C: adb <= system/core/adb/transport_local.c
acp: unable to open '/index.html': Permission denied
host C: adb <= system/core/adb/usb_vendors.c
make[1]: **\* [/index.html] Error 1
make[1]: **\* Waiting for unfinished jobs....
host Executable: aapt (out/host/linux-x86/obj/EXECUTABLES/aapt_intermediates/aapt)
system/core/adb/transport_local.c:321: warning: extra tokens at end of #endif directive

**Comment by jammink** [comment]
I and mikeh are seeing the same issue - for me when building for Nexus S (non ICS):

Me:  http://pastebin.mozilla.org/1561073
mikeh:  http://pastebin.mozilla.org/1560722

**Comment by mikeaich** [comment]
Ran 'make sync' and 'make config-nexuss-ics' around 12:30pm EDT today, and 'make gonk' completed successfully.

**Comment by jammink** [comment]
I also ran make gonk successfully today with same steps.

**Comment by michaelwu** [comment]
Closing the issue then.

**Comment by joneschrisg** [comment]
Fixed by fd32ad8833e43dcc91f5541417938ee65ed37bf7, 035968e16ad4bdb6ca5e2aef1ec57b045fc26b4c and some sub-repository changes.
