### ISSUE TITLE
black screen upon launching emulator

### ISSUE THREAD

**Issue by jonallengriffin** [andreasgal/B2G#265]
This appeared with commit http://github.com/andreasgal/B2G/commit/da8845d3d57767501361641913f32a02cd31d7e3.   Related to https://github.com/andreasgal/B2G/issues/261?

Logcat:

I/Gecko   (   34): Logging GL tracing output to (null)/firefox.trace
I/Gecko   (   34): Attempting load of /data/local/egltrace.so
I/Gecko   (   34): Attempting load of libEGL.so
D/libEGL  (   34): egl.cfg not found, using default config
D/libEGL  (   34): loaded /system/lib/egl/libGLES_android.so
I/Gecko   (   34): Extensions: EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_ANDROID_image_native_buffer EGL_ANDROID_swap_rectangle  0x45
I/Gecko   (   34): Extensions length: 113
I/Gecko   (   34): Failed to create EGL config!
I/Gonk    (   34): Failed to create GL context for fb, trying /dev/graphics/fb0
D/EventHub(   34): No input device configuration file found for device 'qwerty2'.
E/Keyboard(   34): Could not determine key map for device 'qwerty2' and no default key maps were found!
I/EventHub(   34): New device: id=1, fd=37, path='/dev/input/event0', name='qwerty2', classes=0x8d, configuration='', keyLayout='', keyCharacterMap='', builtinKeyboard=false
E/EventHub(   34): could not get driver version for /dev/input/mouse0, Not a typewriter
E/EventHub(   34): could not get driver version for /dev/input/mice, Not a typewriter
I/InputReader(   34): Device reconfigured: id=1, name='qwerty2', surface size is now 480x856, mode is 2
I/InputReader(   34): Device added: id=1, name='qwerty2', sources=0x80100109
E/GeckoConsole(   34): Attempt to use JS function on a different thread calling nsIDirectoryServiceProvider.getFile. JS objects may not be shared across threads.
I/Gecko   (   34): **\* AUS:SVC Checker:getUpdateURL - update URL: http://update.boot2gecko.org/m2.5/updates.xml
E/GeckoConsole(   34): AUS:SVC Checker:getUpdateURL - update URL: http://update.boot2gecko.org/m2.5/updates.xml
I/Gecko   (   34): **\* AUS:SVC gCanCheckForUpdates - able to check for updates
E/GeckoConsole(   34): AUS:SVC gCanCheckForUpdates - able to check for updates
I/Gecko   (   34): **\* AUS:SVC Checker:checkForUpdates - sending request to: http://update.boot2gecko.org/m2.5/updates.xml
E/GeckoConsole(   34): AUS:SVC Checker:checkForUpdates - sending request to: http://update.boot2gecko.org/m2.5/updates.xml
I/Gecko   (   34): **\* UTM:SVC TimerManager:notify - notified @mozilla.org/updates/update-service;1
E/GeckoConsole(   34): UTM:SVC TimerManager:notify - notified @mozilla.org/updates/update-service;1
I/GeckoDump(   34): Opened socket on 9999
I/Gecko   (   34): SmsDatabaseService: Database needs upgrade: sms 0 1
I/Gecko   (   34): SmsDatabaseService: Correct new database version: true
I/Gecko   (   34): SmsDatabaseService: New database
I/Gecko   (   34): SmsDatabaseService: Created object stores and indexes

**Comment by malini** [comment]
I'm having a similar issue with the ics qemu build:

I/Gecko   (  321): Logging GL tracing output to /system/b2g/firefox.trace
I/Gecko   (  321): Attempting load of /data/local/egltrace.so
I/Gecko   (  321): Attempting load of libEGL.so
D/libEGL  (  321): Emulator without GPU support detected. Fallback to software renderer.
D/libEGL  (  321): loaded /system/lib/egl/libGLES_android.so
I/Gecko   (  321): Extensions: EGL_KHR_image_base EGL_ANDROID_image_native_buffer  0x45
I/Gecko   (  321): Extensions length: 51
I/Gecko   (  321): Failed to create EGL config!
I/Gonk    (  321): Failed to create GL context for fb, trying /dev/graphics/fb0
I/EventHub(  321): New device: id=1, fd=40, path='/dev/input/event0', name='qwerty2', classes=0x2d, configuration='/system/usr/idc/qwerty2.idc', keyLayout='/system/usr/keylayout/qwerty.kl', keyCharacterMap='/system/usr/keychars/qwerty2.kcm', builtinKeyboard=true
E/EventHub(  321): could not get driver version for /dev/input/mouse0, Not a typewriter
E/EventHub(  321): could not get driver version for /dev/input/mice, Not a typewriter
I/InputReader(  321): Device reconfigured: id=0, name='qwerty2', surface size is now 480x854, mode is 1
I/InputReader(  321): Device added: id=0, name='qwerty2', sources=0x00001303
I/ServiceManager(  321): Waiting for service batteryinfo...
E/GeckoConsole(  321): Attempt to use JS function on a different thread calling nsIDirectoryServiceProvider.getFile. JS objects may not be shared across threads.
I/GeckoDump(  321): Opened socket on 9999
I/ServiceManager(  321): Waiting for service batteryinfo...
E/GeckoConsole(  321): [JavaScript Error: "The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must to be declared in the document or in the transfer protocol." {file: "data:text/html,%3C!DOCTYPE%20html>%3Cbody%20style='background:black;'>" line: 0}]
W/AudioFlinger(  319): Thread AudioOut_1 cannot connect to the power manager service
I/Gecko   (  321): RIL Worker: voice registration state: 1,ffffffff,ffffffff
I/Gecko   (  321): ======================= webapi+apps.js ======================= 
I/ServiceManager(  321): Waiting for service batteryinfo...
I/ServiceManager(  321): Waiting for service batteryinfo...

**Comment by jonallengriffin** [comment]
The qemu builds still have the same symptoms, but the logcat is different.  The b2g process keeps dying and getting restarted with this log output:

E/profiler(   83): Registering start/stop signal
I/Gonk    (   83): Socket open for RIL
I/gralloc (   83): using (fd=22)
I/gralloc (   83): id           = 
I/gralloc (   83): xres         = 480 px
I/gralloc (   83): yres         = 854 px
I/gralloc (   83): xres_virtual = 480 px
I/gralloc (   83): yres_virtual = 1708 px
I/gralloc (   83): bpp          = 16
I/gralloc (   83): r            = 11:5
I/gralloc (   83): g            =  5:6
I/gralloc (   83): b            =  0:5
I/gralloc (   83): width        = 74 mm (164.756760 dpi)
I/gralloc (   83): height       = 131 mm (165.584732 dpi)
I/gralloc (   83): refresh rate = 243.95 Hz
D/FramebufferNativeWindow(   83): mNumBuffers = 2
I/Gecko   (   83): Logging GL tracing output to (null)/firefox.trace
I/Gecko   (   83): Attempting load of /data/local/egltrace.so
I/Gecko   (   83): Attempting load of libEGL.so
D/libEGL  (   83): egl.cfg not found, using default config
D/libEGL  (   83): loaded /system/lib/egl/libGLES_android.so
I/Gecko   (   83): Extensions: EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_ANDROID_image_native_buffer EGL_ANDROID_swap_rectangle  0x45
I/Gecko   (   83): Extensions length: 113
I/Gecko   (   83): Failed to create EGL config!
I/Gonk    (   83): Failed to create GL context for fb, trying /dev/graphics/fb0
D/EventHub(   83): No input device configuration file found for device 'qwerty2'.
E/Keyboard(   83): Could not determine key map for device 'qwerty2' and no default key maps were found!
I/EventHub(   83): New device: id=1, fd=38, path='/dev/input/event0', name='qwerty2', classes=0x8d, configuration='', keyLayout='', keyCharacterMap='', builtinKeyboard=false
E/EventHub(   83): could not get driver version for /dev/input/mouse0, Not a typewriter
E/EventHub(   83): could not get driver version for /dev/input/mice, Not a typewriter
I/InputReader(   83): Device reconfigured: id=1, name='qwerty2', surface size is now 480x856, mode is 2
I/InputReader(   83): Device added: id=1, name='qwerty2', sources=0x8010210b
I/DEBUG   (   81): debuggerd committing suicide to free the zombie!
I/ServiceManager(   28): service 'media.audio_flinger' died
I/ServiceManager(   28): service 'media.audio_policy' died
I/ServiceManager(   28): service 'media.player' died
I/ServiceManager(   28): service 'media.camera' died
I/        (  108): ServiceManager: 0xad50
D/AudioHardwareInterface(  108): setMode(NORMAL)
I/CameraService(  108): CameraService started (pid=108)
I/AudioFlinger(  108): AudioFlinger's thread 0xc658 ready to run
I/DEBUG   (  113): debuggerd: Apr 13 2012 12:07:16

**Comment by ltedone** [comment]
I've got the same issue building for the emulator. This is what the terminal shows:

emulator: autoconfig: -system /media/DATA/B2G/glue/gonk/out/target/product/generic//system.img
emulator: autoconfig: -ramdisk /media/DATA/B2G/glue/gonk/out/target/product/generic//ramdisk.img
emulator: autoconfig: -datadir /media/DATA/B2G/glue/gonk/out/target/product/generic/
emulator: Found target ABI=armeabi, architecture=arm
emulator: Found target API level: 10
emulator: using core hw config path: /media/DATA/B2G/glue/gonk/out/target/product/generic//hardware-qemu.ini
emulator: keyset loaded from: /home/luigi/.android/default.keyset
emulator: trying to load skin file '/media/DATA/B2G/glue/gonk/development/tools/emulator/skins/WVGA854/layout'
emulator: adjusting LCD dimensions to (480x856x)
emulator: skin network speed: 'full'
emulator: skin network delay: 'none'
emulator: autoconfig: -ramdisk /media/DATA/B2G/glue/gonk/out/target/product/generic//ramdisk.img
emulator: Using initial system image: /media/DATA/B2G/glue/gonk/out/target/product/generic//system.img
emulator: autoconfig: -initdata /media/DATA/B2G/glue/gonk/out/target/product/generic//userdata.img
emulator: autoconfig: -sdcard /media/DATA/B2G/glue/gonk/out/target/product/generic//system.img
emulator: Physical RAM size: 512MB

emulator: Found target ABI=armeabi
Content of hardware configuration file:
  hw.cpu.arch = arm
  hw.cpu.model = 
  hw.ramSize = 512
  hw.touchScreen = yes
  hw.trackBall = yes
  hw.keyboard = yes
  hw.keyboard.lid = yes
  hw.keyboard.charmap = qwerty2
  hw.dPad = yes
  hw.gsmModem = yes
  hw.camera = no
  hw.camera.maxHorizontalPixels = 640
  hw.camera.maxVerticalPixels = 480
  hw.gps = yes
  hw.battery = yes
  hw.accelerometer = yes
  hw.audioInput = yes
  hw.audioOutput = yes
  hw.sdCard = yes
  hw.sdCard.path = /media/DATA/B2G/glue/gonk/out/target/product/generic//system.img
  disk.cachePartition = yes
  disk.cachePartition.path = 
  disk.cachePartition.size = 66m
  hw.lcd.width = 480
  hw.lcd.height = 856
  hw.lcd.depth = 16
  hw.lcd.density = 160
  hw.lcd.backlight = yes
  hw.gpu.enabled = no
  vm.heapSize = 48
  hw.sensors.proximity = yes
  kernel.path = /media/DATA/B2G/boot/kernel-android-qemu/arch/arm/boot/zImage
  kernel.parameters =  android.checkjni=1
  disk.ramdisk.path = /media/DATA/B2G/glue/gonk/out/target/product/generic//ramdisk.img
  disk.systemPartition.initPath = /media/DATA/B2G/glue/gonk/out/target/product/generic//system.img
  disk.systemPartition.size = 512m
  disk.dataPartition.path = /media/DATA/B2G/glue/gonk/out/target/product/generic/userdata.img
  disk.dataPartition.size = 512m
  disk.snapStorage.path = 
  avd.name = <build>
.
QEMU options list:
emulator: argv[00] = "/media/DATA/B2G/glue/gonk/out/host/linux-x86/bin/emulator-arm"
emulator: argv[01] = "-cpu"
emulator: argv[02] = "cortex-a8"
emulator: argv[03] = "-android-hw"
emulator: argv[04] = "/media/DATA/B2G/glue/gonk/out/target/product/generic//hardware-qemu.ini"
Concatenated QEMU options:
 /media/DATA/B2G/glue/gonk/out/host/linux-x86/bin/emulator-arm -cpu cortex-a8 -android-hw /media/DATA/B2G/glue/gonk/out/target/product/generic//hardware-qemu.ini
emulator: registered 'boot-properties' qemud service
emulator: nand_add_dev: system,size=0x20000000,initfile=/media/DATA/B2G/glue/gonk/out/target/product/generic//system.img
emulator: mapping 'system' NAND image to /tmp/android-luigi/emulator-uiBOIx
emulator: rounding devsize up to a full eraseunit, now 20004000

emulator: nand_add_dev: userdata,size=0x20000000,file=/media/DATA/B2G/glue/gonk/out/target/product/generic/userdata.img
emulator: rounding devsize up to a full eraseunit, now 20004000

emulator: registered 'boot-properties' qemud service
emulator: Adding boot property: 'dalvik.vm.heapsize' = '48m'
emulator: Adding boot property: 'qemu.sf.lcd_density' = '160'
emulator: nand_add_dev: cache,size=0x4200000
emulator: mapping 'cache' NAND image to /tmp/android-luigi/emulator-dl8bxZ
emulator: Kernel parameters: qemu.gles=0 qemu=1 console=ttyS0 android.qemud=ttyS1 android.checkjni=1 ndns=1
emulator: Trace file name is not set

emulator: autoconfig: -scale 0.940529
emulator: emulator window was out of view and was recentered

emulator: control console listening on port 5554, ADB on port 5555
emulator: can't connect to ADB server: Connection refused
emulator: ping program: /media/DATA/B2G/glue/gonk/out/host/linux-x86/bin/ddms
goldfish_fb_get_pixel_format:167: display surface,pixel format:
  bits/pixel:  16
  bytes/pixel: 2
  depth:       16
  red:         bits=5 mask=0xf800 shift=11 max=0x1f
  green:       bits=6 mask=0x7e0 shift=5 max=0x3f
  blue:        bits=5 mask=0x1f shift=0 max=0x1f
  alpha:       bits=0 mask=0x0 shift=0 max=0x0

**Comment by jonallengriffin** [comment]
current logcat in qemu-ics:

I/Gecko   (   41): Logging GL tracing output to /system/b2g/firefox.trace
I/Gecko   (   41): Attempting load of /data/local/egltrace.so
I/Gecko   (   41): Attempting load of libEGL.so
D/libEGL  (   41): Emulator without GPU support detected. Fallback to software renderer.
D/libEGL  (   41): loaded /system/lib/egl/libGLES_android.so
I/Gecko   (   41): Extensions: EGL_KHR_image_base EGL_ANDROID_image_native_buffer  0x45
I/Gecko   (   41): Extensions length: 51
I/Gecko   (   41): Failed to create EGL config!
I/Gonk    (   41): Failed to create GL context for fb, trying /dev/graphics/fb0
I/EventHub(   41): New device: id=1, fd=36, path='/dev/input/event0', name='qwerty2', classes=0x2d, configuration='/system/usr/idc/qwerty2.idc', keyLayout='/system/usr/keylayout/qwerty.kl', keyCharacterMap='/system/usr/keychars/qwerty2.kcm', builtinKeyboard=true
E/EventHub(   41): could not get driver version for /dev/input/mouse0, Not a typewriter
E/EventHub(   41): could not get driver version for /dev/input/mice, Not a typewriter
I/InputReader(   41): Device reconfigured: id=0, name='qwerty2', surface size is now 480x854, mode is 1
I/InputReader(   41): Device added: id=0, name='qwerty2', sources=0x00011307
D/VoldCmdListener(   31): volume mount sdcard
E/GeckoConsole(   41): Attempt to use JS function on a different thread calling nsIDirectoryServiceProvider.getFile. JS objects may not be shared across threads.
I/GeckoDump(   41): Opened socket on 9999
W/AudioFlinger(   36): Thread AudioOut_1 cannot connect to the power manager service
E/GeckoConsole(   41): [JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIAudioManager.masterVolume]" {file: "chrome://browser/content/shell.js" line: 106}]
I/Gecko   (   41): RIL Worker: DateTimeZone string 12/04/17:01:22:29-28:1:America!Los_Angeles
E/WifiHW  (   41): Cannot open "/system/etc/wifi/wpa_supplicant.conf": No such file or directory
E/WifiHW  (   41): Wi-Fi will not be enabled
I/Gecko   (   41): **\* AUS:SVC Checker:getUpdateURL - update URL: http://update.boot2gecko.org/m2.5/updates.xml
E/GeckoConsole(   41): AUS:SVC Checker:getUpdateURL - update URL: http://update.boot2gecko.org/m2.5/updates.xml
I/Gecko   (   41): **\* AUS:SVC gCanCheckForUpdates - able to check for updates
E/GeckoConsole(   41): AUS:SVC gCanCheckForUpdates - able to check for updates
I/Gecko   (   41): **\* AUS:SVC Checker:checkForUpdates - sending request to: http://update.boot2gecko.org/m2.5/updates.xml
E/GeckoConsole(   41): AUS:SVC Checker:checkForUpdates - sending request to: http://update.boot2gecko.org/m2.5/updates.xml
I/Gecko   (   41): **\* UTM:SVC TimerManager:notify - notified @mozilla.org/updates/update-service;1
E/GeckoConsole(   41): UTM:SVC TimerManager:notify - notified @mozilla.org/updates/update-service;1
I/Gecko   (   41): **\* AUS:SVC Checker:onError - request.status: 2152398878
E/GeckoConsole(   41): AUS:SVC Checker:onError - request.status: 2152398878
I/Gecko   (   41): **\* AUS:SVC getStatusTextFromCode - transfer error: Update server not found (check your internet connection), code: 2152398878
E/GeckoConsole(   41): AUS:SVC getStatusTextFromCode - transfer error: Update server not found (check your internet connection), code: 2152398878
I/Gecko   (   41): **\* AUS:SVC UpdateService:notify:listener - error during background update: Update server not found (check your internet connection)
E/GeckoConsole(   41): AUS:SVC UpdateService:notify:listener - error during background update: Update server not found (check your internet connection)
I/Gecko   (   41): **\* UTM:SVC TimerManager:notify - notified @mozilla.org/browser/search-service;1
E/GeckoConsole(   41): UTM:SVC TimerManager:notify - notified @mozilla.org/browser/search-service;1
E/GeckoConsole(   41): [JavaScript Warning: "WARN addons.repository: cacheEnabled: Couldn't get pref: extensions.getAddons.cache.enabled" {file: "resource://gre/modules/AddonRepository.jsm" line: 426}]
I/Gecko   (   41): **\* UTM:SVC TimerManager:notify - notified @mozilla.org/addons/integration;1
E/GeckoConsole(   41): UTM:SVC TimerManager:notify - notified @mozilla.org/addons/integration;1

**Comment by tsschnoc** [comment]
Hi

yesterday, mdas told me to do this as a workaround and then use "make config-qemu-ics" instead of "config-qemu".

comment out https://hg.mozilla.org/mozilla-central/file/35e13f42ee8a/widget/gonk/nsAppShell.cpp#l596
apply https://bugzilla.mozilla.org/show_bug.cgi?id=746429

As a result, the emulator starts now, but nor shows the message: "Server not found ... homescreen.gaiamobile.org not found ..... check yout Wi-Fi connection"

in the logcat I see this lines:
E/WifiHW  (   41): Cannot open "/system/etc/wifi/wpa_supplicant.conf": No such file or directory
E/WifiHW  (   41): Wi-Fi will not be enabled

So I suspect the wifi driver to have problems.

Any ideas

Thomas

**Comment by jamesho86** [comment]
any update on this issue?

**Comment by malini** [comment]
as of last week, you can build the qemu-ics emulator, but to get a functioning screen, you have to remove the profile:  

adb shell
stop b2g
rm -R /data/b2g/mozilla
start b2g

this will restart the b2g process with a new profile. I'm not sure what causes the original error.

**Comment by marti1125** [comment]
emulator: autoconfig: -system /home/willy/B2G/glue/gonk/out/target/product/generic//system.img
emulator: autoconfig: -ramdisk /home/willy/B2G/glue/gonk/out/target/product/generic//ramdisk.img
emulator: autoconfig: -datadir /home/willy/B2G/glue/gonk/out/target/product/generic/
emulator: Found target ABI=armeabi, architecture=arm
emulator: Found target API level: 10
emulator: using core hw config path: /home/willy/B2G/glue/gonk/out/target/product/generic//hardware-qemu.ini
emulator: keyset loaded from: /home/willy/.android/default.keyset
emulator: trying to load skin file '/home/willy/B2G/glue/gonk/development/tools/emulator/skins/WVGA854/layout'
emulator: adjusting LCD dimensions to (480x856x)
emulator: skin network speed: 'full'
emulator: skin network delay: 'none'
emulator: autoconfig: -ramdisk /home/willy/B2G/glue/gonk/out/target/product/generic//ramdisk.img
emulator: Using initial system image: /home/willy/B2G/glue/gonk/out/target/product/generic//system.img
emulator: autoconfig: -initdata /home/willy/B2G/glue/gonk/out/target/product/generic//userdata.img
emulator: autoconfig: -sdcard /home/willy/B2G/glue/gonk/out/target/product/generic//system.img
emulator: Physical RAM size: 512MB

emulator: Found target ABI=armeabi
Content of hardware configuration file:
  hw.cpu.arch = arm
  hw.cpu.model = 
  hw.ramSize = 512
  hw.touchScreen = yes
  hw.trackBall = yes
  hw.keyboard = yes
  hw.keyboard.lid = yes
  hw.keyboard.charmap = qwerty2
  hw.dPad = yes
  hw.gsmModem = yes
  hw.camera = no
  hw.camera.maxHorizontalPixels = 640
  hw.camera.maxVerticalPixels = 480
  hw.gps = yes
  hw.battery = yes
  hw.accelerometer = yes
  hw.audioInput = yes
  hw.audioOutput = yes
  hw.sdCard = yes
  hw.sdCard.path = /home/willy/B2G/glue/gonk/out/target/product/generic//system.img
  disk.cachePartition = yes
  disk.cachePartition.path = 
  disk.cachePartition.size = 66m
  hw.lcd.width = 480
  hw.lcd.height = 856
  hw.lcd.depth = 16
  hw.lcd.density = 160
  hw.lcd.backlight = yes
  hw.gpu.enabled = no
  vm.heapSize = 48
  hw.sensors.proximity = yes
  kernel.path = /home/willy/B2G/boot/kernel-android-qemu/arch/arm/boot/zImage
  kernel.parameters =  android.checkjni=1
  disk.ramdisk.path = /home/willy/B2G/glue/gonk/out/target/product/generic//ramdisk.img
  disk.systemPartition.initPath = /home/willy/B2G/glue/gonk/out/target/product/generic//system.img
  disk.systemPartition.size = 512m
  disk.dataPartition.path = /home/willy/B2G/glue/gonk/out/target/product/generic/userdata.img
  disk.dataPartition.size = 512m
  disk.snapStorage.path = 
  avd.name = <build>
.
QEMU options list:
emulator: argv[00] = "/home/willy/B2G/glue/gonk/out/host/linux-x86/bin/emulator-arm"
emulator: argv[01] = "-cpu"
emulator: argv[02] = "cortex-a8"
emulator: argv[03] = "-android-hw"
emulator: argv[04] = "/tmp/android-willy/emulator-l7cF5p"
Concatenated QEMU options:
 /home/willy/B2G/glue/gonk/out/host/linux-x86/bin/emulator-arm -cpu cortex-a8 -android-hw /tmp/android-willy/emulator-l7cF5p
emulator: registered 'boot-properties' qemud service
emulator: nand_add_dev: system,size=0x20000000,initfile=/home/willy/B2G/glue/gonk/out/target/product/generic//system.img
emulator: mapping 'system' NAND image to /tmp/android-willy/emulator-UqRYUI
emulator: rounding devsize up to a full eraseunit, now 20004000

WARNING: Data partition already in use. Changes will not persist!
emulator: nand_add_dev: userdata,size=0x20000000
emulator: mapping 'userdata' NAND image to /tmp/android-willy/emulator-okf9nr
emulator: rounding devsize up to a full eraseunit, now 20004000

WARNING: SD Card image already in use: /home/willy/B2G/glue/gonk/out/target/product/generic//system.img
emulator: registered 'boot-properties' qemud service
emulator: Adding boot property: 'dalvik.vm.heapsize' = '48m'
emulator: Adding boot property: 'qemu.sf.lcd_density' = '160'
emulator: nand_add_dev: cache,size=0x4200000
emulator: mapping 'cache' NAND image to /tmp/android-willy/emulator-rXcGqf
emulator: Kernel parameters: qemu.gles=0 qemu=1 console=ttyS0 android.qemud=ttyS1 android.checkjni=1 ndns=1
emulator: Trace file name is not set

emulator: autoconfig: -scale 0.802863
emulator: emulator window was out of view and was recentered

emulator: control console listening on port 5556, ADB on port 5557
emulator: sent '0012host:emulator:5557' to ADB server
emulator: ping program: /home/willy/B2G/glue/gonk/out/host/linux-x86/bin/ddms
goldfish_fb_get_pixel_format:167: display surface,pixel format:
  bits/pixel:  16
  bytes/pixel: 2
  depth:       16
  red:         bits=5 mask=0xf800 shift=11 max=0x1f
  green:       bits=6 mask=0x7e0 shift=5 max=0x3f
  blue:        bits=5 mask=0x1f shift=0 max=0x1f
  alpha:       bits=0 mask=0x0 shift=0 max=0x0
emulator: User configuration saved to /home/willy/.android/emulator-user.ini
willy@willy-K52Dr:~/B2G$ adb shell

# stop b2g

# rm -R /data/b2g/mozilla

# start b2g

# willy@willy-K52Dr:~/B2G$ ./emu.sh

emulator: autoconfig: -system /home/willy/B2G/glue/gonk/out/target/product/generic//system.img
emulator: autoconfig: -ramdisk /home/willy/B2G/glue/gonk/out/target/product/generic//ramdisk.img
emulator: autoconfig: -datadir /home/willy/B2G/glue/gonk/out/target/product/generic/
emulator: Found target ABI=armeabi, architecture=arm
emulator: Found target API level: 10
emulator: using core hw config path: /home/willy/B2G/glue/gonk/out/target/product/generic//hardware-qemu.ini
emulator: keyset loaded from: /home/willy/.android/default.keyset
emulator: trying to load skin file '/home/willy/B2G/glue/gonk/development/tools/emulator/skins/WVGA854/layout'
emulator: adjusting LCD dimensions to (480x856x)
emulator: skin network speed: 'full'
emulator: skin network delay: 'none'
emulator: autoconfig: -ramdisk /home/willy/B2G/glue/gonk/out/target/product/generic//ramdisk.img
emulator: Using initial system image: /home/willy/B2G/glue/gonk/out/target/product/generic//system.img
emulator: autoconfig: -initdata /home/willy/B2G/glue/gonk/out/target/product/generic//userdata.img
emulator: autoconfig: -sdcard /home/willy/B2G/glue/gonk/out/target/product/generic//system.img
emulator: Physical RAM size: 512MB

emulator: Found target ABI=armeabi
Content of hardware configuration file:
  hw.cpu.arch = arm
  hw.cpu.model = 
  hw.ramSize = 512
  hw.touchScreen = yes
  hw.trackBall = yes
  hw.keyboard = yes
  hw.keyboard.lid = yes
  hw.keyboard.charmap = qwerty2
  hw.dPad = yes
  hw.gsmModem = yes
  hw.camera = no
  hw.camera.maxHorizontalPixels = 640
  hw.camera.maxVerticalPixels = 480
  hw.gps = yes
  hw.battery = yes
  hw.accelerometer = yes
  hw.audioInput = yes
  hw.audioOutput = yes
  hw.sdCard = yes
  hw.sdCard.path = /home/willy/B2G/glue/gonk/out/target/product/generic//system.img
  disk.cachePartition = yes
  disk.cachePartition.path = 
  disk.cachePartition.size = 66m
  hw.lcd.width = 480
  hw.lcd.height = 856
  hw.lcd.depth = 16
  hw.lcd.density = 160
  hw.lcd.backlight = yes
  hw.gpu.enabled = no
  vm.heapSize = 48
  hw.sensors.proximity = yes
  kernel.path = /home/willy/B2G/boot/kernel-android-qemu/arch/arm/boot/zImage
  kernel.parameters =  android.checkjni=1
  disk.ramdisk.path = /home/willy/B2G/glue/gonk/out/target/product/generic//ramdisk.img
  disk.systemPartition.initPath = /home/willy/B2G/glue/gonk/out/target/product/generic//system.img
  disk.systemPartition.size = 512m
  disk.dataPartition.path = /home/willy/B2G/glue/gonk/out/target/product/generic/userdata.img
  disk.dataPartition.size = 512m
  disk.snapStorage.path = 
  avd.name = <build>
.
QEMU options list:
emulator: argv[00] = "/home/willy/B2G/glue/gonk/out/host/linux-x86/bin/emulator-arm"
emulator: argv[01] = "-cpu"
emulator: argv[02] = "cortex-a8"
emulator: argv[03] = "-android-hw"
emulator: argv[04] = "/home/willy/B2G/glue/gonk/out/target/product/generic//hardware-qemu.ini"
Concatenated QEMU options:
 /home/willy/B2G/glue/gonk/out/host/linux-x86/bin/emulator-arm -cpu cortex-a8 -android-hw /home/willy/B2G/glue/gonk/out/target/product/generic//hardware-qemu.ini
emulator: registered 'boot-properties' qemud service
emulator: nand_add_dev: system,size=0x20000000,initfile=/home/willy/B2G/glue/gonk/out/target/product/generic//system.img
emulator: mapping 'system' NAND image to /tmp/android-willy/emulator-cQHAri
emulator: rounding devsize up to a full eraseunit, now 20004000

emulator: nand_add_dev: userdata,size=0x20000000,file=/home/willy/B2G/glue/gonk/out/target/product/generic/userdata.img
emulator: rounding devsize up to a full eraseunit, now 20004000

emulator: registered 'boot-properties' qemud service
emulator: Adding boot property: 'dalvik.vm.heapsize' = '48m'
emulator: Adding boot property: 'qemu.sf.lcd_density' = '160'
emulator: nand_add_dev: cache,size=0x4200000
emulator: mapping 'cache' NAND image to /tmp/android-willy/emulator-lglnos
emulator: Kernel parameters: qemu.gles=0 qemu=1 console=ttyS0 android.qemud=ttyS1 android.checkjni=1 ndns=1
emulator: Trace file name is not set

emulator: autoconfig: -scale 0.802863
emulator: emulator window was out of view and was recentered

emulator: control console listening on port 5556, ADB on port 5557
emulator: sent '0012host:emulator:5557' to ADB server
emulator: ping program: /home/willy/B2G/glue/gonk/out/host/linux-x86/bin/ddms
goldfish_fb_get_pixel_format:167: display surface,pixel format:
  bits/pixel:  16
  bytes/pixel: 2
  depth:       16
  red:         bits=5 mask=0xf800 shift=11 max=0x1f
  green:       bits=6 mask=0x7e0 shift=5 max=0x3f
  blue:        bits=5 mask=0x1f shift=0 max=0x1f
  alpha:       bits=0 mask=0x0 shift=0 max=0x0
emulator: User configuration saved to /home/willy/.android/emulator-user.ini

**Comment by jonallengriffin** [comment]
This is resolved.

**Comment by lltboe** [comment]
how did you resolve Black Screen Problem?

**Comment by toniher** [comment]
I have the black screen as well. No matter I removed /data/b2G/mozilla

**Comment by lltboe** [comment]
Can you tell me where is the /data/b2G/mozilla directory? I have gitted the lastest 32-bit source code but no /data/b2G/mozilla.

**Comment by jonathanagriffin** [comment]
See also https://github.com/mozilla-b2g/B2G/issues/51

**Comment by ibrahimasarr** [comment]
Black screen is only "sleep", hit home key to wake up!
