### ISSUE TITLE
Apps (Wikipedia, NY Times, etc.) disappear after self-reset

### ISSUE THREAD

**Issue by ttaubert** [andreasgal/B2G#268]
On my Nexus S the third homescreen pane contains apps like Wikipedia and NY Times. When B2G resets itself this pane becomes almost empty and all those apps disappear. "Tasks" loses its icon and "Market" transforms into "Homescreen" without an icon. Rebooting the phone doesn't help either.

"make install-gaia" fixes this until the next reset.

**Comment by robhawkes** [comment]
I've also noticed this issue, as have others on the DevEngage team. Only way to get the lost apps back is to re-install Gaia onto the device.
