### ISSUE TITLE
no mozconfig when building qemu-ics

### ISSUE THREAD

**Issue by jonallengriffin** [andreasgal/B2G#270]
After doing:

make mrproper
make config-qemu-ics
make gonk

this error appears:

Specified MOZCONFIG "/home/jgriffin/jB2G/glue/gonk-ics/gonk-misc/default-gecko-config" does not exist!
make[3]: Entering directory `/home/jgriffin/jB2G/gecko'
/home/jgriffin/jB2G/gecko/.mozconfig.mk:6: **\* Fix above errors before continuing..  Stop.

**Comment by michaelwu** [comment]
This should be fixed. I forgot to push some new files.

**Comment by jonallengriffin** [comment]
This is fixed.
