### ISSUE TITLE
Wifi is not Working on Galaxy S II. It always shows scanning

### ISSUE THREAD

**Issue by shollmann** [andreasgal/B2G#277]
I am running B2G (2012-03-19 10:42:52) on a Samsung Galaxy S II.

I go to setting- Wifi- Turn it on and then I see "scanning" all the time.

I trying rebooting and turning it off.

If you need any other information, just let me know.

**Comment by vingtetun** [comment]
On 24/04/2012 19:26, shollmann wrote:

> I am running B2G (2012-03-19 10:42:52) on a Samsung Galaxy S II.
> 
> I go to setting- Wifi- Turn it on and then I see "scanning" all the time.
> 
> I trying rebooting and turning it off.
> 
> If you need any other information, just let me know.

@fabiencazenave is is known?

**Comment by kumar303** [comment]
same here. Can anyone recommend an older build that has working wifi? I tried with today's build and also back to 4/8, 4/7...

**Comment by adamkalis** [comment]
I have also this problem.
Edit:
It seems this problem has to do with Gaia.
1. I install the latest version of Gaia.
2. When I go at the settings -> wifi then, after a while, it shows the available networks (without showing the scanning text and the image). 
3. After that and without any notice under the wifi text (the one next to the check box) it connects to wifi.
4. A notification shows up and says that there is an update about settings
5. Tap on this notification and then go on settings -> wifi again
6. There is the infinite scanning (text and image)

I don't know if this is useful but i have noticed that before the update there is one file under the directory /data/local/OfflineCache/F/C with the name FBF0ACDE9B5D99-0.

After the update there are two more files under the same directory the FBF0ACDE9B5D99-1 and the FBF0ACDE9B5D99-2.

I have no idea if these two files are right but at the "scanning" code they use the old(?) "screen.mozEnabled" that has been changed with "navigator.mozPower.screenEnabled".

I have done manually this change (pull, change and push) and seems that "scanning" works fine.

Unfortunately other problems show up for example by selecting a wifi network it connects to it but under the wifi text says it is offline.

**Comment by jammink** [comment]
@shollman, @kumar303 - could you guys do:
$ adb reboot
$ adb logcat

and paste the logcat, for example to pastebin.mozilla.org

and then attach a link?  That would help the devs with their diagnoses.  Thanks!

**Comment by jammink** [comment]
@kumar303  - it's really hard to get older b2g builds (unless b2gbuilds.org has an archive of sorts) - and not much point - since we're need to find these bugs in latest version!  Is wifi absolutely not connecting for you at all?

**Comment by lcamacho** [comment]
@jammink this is what logcat shows me http://pastebin.mozilla.org/1598819

**Comment by adamkalis** [comment]
@jammink my log at http://pastebin.mozilla.org/1599088 (the dashed comments are mine)
This is what I get when I experience the behavior that I described at my previous comment (until the step 6)

**Comment by vingtetun** [comment]
@fabi1cazenave Is it known? (miistype the name the first time...)

**Comment by shollmann** [comment]
This is my log: http://pastebin.mozilla.org/1599112

**Comment by kumar303** [comment]
I updated to the latest build and also grabbed a fresh gaia checkout. My log is similar: http://pastebin.mozilla.org/1599194

**Comment by kumar303** [comment]
My pastebin expired. Here is the log again: http://pastebin.mozilla.org/1602591 (right at the bottom is what happens when I wait for wifi, nothing ever connects)

**Comment by kumar303** [comment]
does anyone have an idea for a wifi fix? The webdev group has an offsite next week where we'll be hacking on b2g apps! Obviously we can use the simulator but it would be cool to install one or two on a real phone.

**Comment by shollmann** [comment]
I added this bug on Gaia: https://github.com/andreasgal/gaia/issues/1313

**Comment by dhylands** [comment]
I ran into this issue as well. I recovered to my android image and reflashed b2g and then wifi started working again.

Unfortunately, recovering to android also recovered some old files into /data/b2g so my gaia was broken again.

**Comment by adamkalis** [comment]
Verified Fixed after the relative landed patch on Gaia (more at https://github.com/andreasgal/gaia/issues/1313)

@shollmann Should we close this issue too?

**Comment by shollmann** [comment]
yeahp. Closing. Thanks
