### ISSUE TITLE
When the status bar is hidden by some app then the unlock screen doesn't show the status bar again

### ISSUE THREAD

**Issue by shollmann** [andreasgal/B2G#278]
Git Commit Info: 2012-03-19 10:42:52

Description
When the status bar is hidden by some app then the unlock screen doesn't show the status bar again

Steps
1 - Open an app (Test UI, Video,) that has a "top bar" which covers the "status bar" (where you have the battery life, time, etc).
2 - Lock the phone
3 - Press the unlock button

If you need anything else, just let me know.

**Comment by davidflanagan** [comment]
@shollmann This sounds like a Gaia issue. Would you report it over at https://github.com/andreasgal/gaia please?

**Comment by vingtetun** [comment]
On 24/04/2012 20:03, shollmann wrote:

> Git Commit Info: 2012-03-19 10:42:52
> 
> Description
> When the status bar is hidden by some app then the unlock screen doesn't show the status bar again
> 
> Steps
> 1 - Open an app (Test UI, Video,) that has a "top bar" which covers the "status bar" (where you have the battery life, time, etc).
> 2 - Lock the phone
> 3 - Press the unlock button
> 
> If you need anything else, just let me know.

Can you file this issue on Gaia instead?

Thanks!

**Comment by shollmann** [comment]
@davidflanagan I found this bug https://github.com/andreasgal/gaia/issues/1151 assigned to you and I think it is the same.
