### ISSUE TITLE
Fix Samsung-provided Galaxy S II kernel

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#28]
We're building the source that Samsung publishes through their website, but the kernel is apparently panicing early in startup.  It's not clear what's going wrong yet.  Something like kgdb over USB, plus rejiggering the USB startup order to make sure it's up soon enough, might be the right way to tackle this.

**Comment by michaelwu** [comment]
Nothing was wrong with it - we just weren't including the rootfs during the kernel build.
