### ISSUE TITLE
libOpenglRender/render_api.h: No such file or directory build error

### ISSUE THREAD

**Issue by malini** [andreasgal/B2G#284]
I've tried to build gonk for qemu-ics and for a nexus S phone, but each time, I would get the following build error:

host C: emulator-arm <= external/qemu/android/protocol/core-commands-qemu.c
external/qemu/vl-android.c: In function 'qemu_main':
external/qemu/vl-android.c:2530:31: warning: variable 'net_boot' set but not used [-Wunused-but-set-variable]
host C: emulator-arm <= external/qemu/android/protocol/ui-commands-qemu.c
host C: emulator-arm <= external/qemu/hw/smc91c111.c
host C: emulator-arm <= external/qemu/block.c
host C: emulator-arm <= external/qemu/blockdev.c
host C: emulator-arm <= external/qemu/block/qcow.c
external/qemu/android/opengles.c:22:40: fatal error: libOpenglRender/render_api.h: No such file or directory
compilation terminated.
make[1]: **\* [out/host/linux-x86/obj/EXECUTABLES/emulator-arm_intermediates/android/opengles.o] Error 1
make[1]: **\* Waiting for unfinished jobs....
external/qemu/hw/smc91c111.c: In function 'smc91c111_do_tx':
external/qemu/hw/smc91c111.c:240:9: warning: variable 'add_crc' set but not used [-Wunused-but-set-variable]
external/qemu/block.c: In function 'bdrv_find_whitelisted_format':
external/qemu/block.c:185:19: warning: array subscript is above array bounds [-Warray-bounds]
external/qemu/block.c: In function 'bdrv_open_common':
external/qemu/block.c:185:19: warning: array subscript is above array bounds [-Warray-bounds]
make[1]: Leaving directory `/home/b2g/Code/B2G_repull/glue/gonk-ics'
make: **\* [gonk] Error 2

This is after a make mrproper, make sync and make config for each type. This was running code with commit number: c9749387a4c80a8955041795a161a3c8d72423dc

**Comment by michaelwu** [comment]
make config-qemu-ics again. We just landed a fix for this

**Comment by malini** [comment]
works fine now, thanks!

**Comment by jonallengriffin** [comment]
ugh, I saw this too and was hoping it was just me!
