### ISSUE TITLE
make flash-only fails consistently on nexus s gingerbread

### ISSUE THREAD

**Issue by jammink** [andreasgal/B2G#290]
git  commit c7af523597d5f97bfd2e69d1c50c38d08d3da30c

pastebin.mozilla.org/1607822

tried flashing several phones, and I'm getting the same error.  Haven't tried yet on ICS

**Comment by philikon** [comment]
Not sure if we still want to support gonk-gb on the Nexus S. I'm not surprised it's not working at least since nobody develops against it. ICS is the way to go IMHO. RESOLVED/WONTFIX?

**Comment by michaelwu** [comment]
Nexus S GB is completely unsupported. It has buggy GL drivers which make it unusable.
