### ISSUE TITLE
Have installer ensure that package manager can work

### ISSUE THREAD

**Issue by ctalbert** [andreasgal/B2G#30]
People sometimes get a message at the end of the install-gecko process that says:
/sbin/sh pm not found
Then this refers to the android package manager not working properly on the device.
The reason it's not working is that it doesn't have permissions to write to /data/system.

I think that if the install-gecko target is modified to ensure this directory is writeable, we can save the user some headaches.

The install target would probably need to do:
adb shell chmod -R 666 /data/system

I have tested that 777 definitely works, but I doubt we need the directory to be executable.

Note that when I had this issue, I also had a further issue that pm was not being located by the system even though it was clearly in the path.  To get around that, I had to do:
adb shell sh /system/bin/pm install -r <apk location>

I'm not sure if the path issue was related to this, or due to some other misconfiguration on my system.

**Comment by joneschrisg** [comment]
It was actually worse, at least on Andreas's phone: the phone couldn't fully start up, and went into an infinite loop trying to finish starting up and failing.  Nothing appeared on screen.

Programs need execute permissions to chdir() into a directory, so we need to use 777.  The /system partition is mounted read-only so granting world write permissions doesn't really matter.

I remember verifying that the image on my host, that the install image is built from, had the right permissions.  I think there's some bug in the installation of the image, possibly in heimdall.

**Comment by jaoo** [comment]
After installing manualy the b2g.apk android package as ctalbert told a browser starts up trying to show a hmtl homescreen but it can not find this file on disc. That file is | /data/local/homescreen.html |, any comment on this?

**Comment by joneschrisg** [comment]
Yes, /data/local/homescreen.html can be whatever home screen UI you choose.  So for example if you're working on a demo UI package that has a homescreen at index.html, then you could push it to /data/local and then create a symlink from homescreen.html to index.html.

Eventually we'll have a basic demo UI committed to the b2g repo, but that's not ready yet.

**Comment by joneschrisg** [comment]
Quick note that,

To fix:
1. $ adb push gecko/objdir-prof-android/dist/b2g-9.0a1.en-US.android-arm.apk /data/local/tmp/b2g.apk
2. $ adb shell
3. # chmod -R 777 /data/system
4. # sh /system/bin/pm install -r /data/local/tmp/b2g.apk
5. # reboot

only step (3) above is needed to fix the problem.  It affects the whole OS, not just the gecko install.  Since we'll be removing these instructions when we add this workaround to the flashing process, no need to worry it about for now.

**Comment by joneschrisg** [comment]
sorry pm, we don't need you anymore.
