### ISSUE TITLE
arm qemu won't boot

### ISSUE THREAD

**Issue by jonallengriffin** [andreasgal/B2G#302]
After making a clobber arm qemu:

./config.sh emulator
./build.sh
./run-emulator.sh

the emulator won't boot.  It stays at a black screen; adb says it is offline so there is no logcat.  Stdout shows:

goldfish_fb_get_pixel_format:167: display surface,pixel format:
  bits/pixel:  16
  bytes/pixel: 2
  depth:       16
  red:         bits=5 mask=0xf800 shift=11 max=0x1f
  green:       bits=6 mask=0x7e0 shift=5 max=0x3f
  blue:        bits=5 mask=0x1f shift=0 max=0x1f
  alpha:       bits=0 mask=0x0 shift=0 max=0x0
repaintOpenGLDisplay not implemented for separate renderer process !!!
repaintOpenGLDisplay not implemented for separate renderer process !!!
repaintOpenGLDisplay not implemented for separate renderer process !!!
repaintOpenGLDisplay not implemented for separate renderer process !!!
repaintOpenGLDisplay not implemented for separate renderer process !!!
repaintOpenGLDisplay not implemented for separate renderer process !!!
repaintOpenGLDisplay not implemented for separate renderer process !!!
repaintOpenGLDisplay not implemented for separate renderer process !!!

**Comment by michaelwu** [comment]
I reproduced the problem. Reverting bionic to 4f05d1c758ba141c617f25251a661ecb66627e9e gets the emulator booting, though I can't see anything on the screen and I'm not sure if it's an issue with my local copy of gecko or something else.

**Comment by jonallengriffin** [comment]
The arm emulator is working again
