### ISSUE TITLE
/usr/bin/ld.bfd.real: cannot find -lGL

### ISSUE THREAD

**Issue by sammaple** [andreasgal/B2G#304]
hello,guys!

I install Ubuntu12.04-64bits in VM.

First ,I make sync successfully,& then I make make config-qemu-ics(this step will down gonk-ics).

All that downed without any problem,  then make gonk,

err occurs :

/usr/bin/ld.bfd.real: cannot find -lGL

can help me? tks

**Comment by sammaple** [comment]
i have ln -s the libGL.so ,but it doesn't work

lrwxrwxrwx 1 root root 35  5月 27 20:15 libGL.so -> /lib/x86_64-linux-gnu/mesa/libGL.so

**Comment by joneschrisg** [comment]
Yes, ubuntu 12.04 scrooged the ia32-libs.  You need to symlink to your real GL impl, as it seems you figured out.

**Comment by sammaple** [comment]
But this doean't work I still stucked on this problem.Anyone encount the same error?

**Comment by sammaple** [comment]
it find i386 lib,i manually create symlinks for
sudo ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/i386-linux-gnu/libGL.so

it works~
