### ISSUE TITLE
/usr/bin/ld.bfd.real: cannot find -lX11

### ISSUE THREAD

**Issue by sammaple** [andreasgal/B2G#305]
hello,guys!

I install Ubuntu12.04-64bits in VM.

First ,I make sync successfully,& then I make make config-qemu-ics(this step will down gonk-ics).

All that downed without any problem, then make gonk,

err occurs :

/usr/bin/ld.bfd.real: cannot find -lX11

can help me? tks

BTY, i have try 
sudo ln -s /lib/x86_64-linux-gnu/libX11.so.6.3.0 /usr/bin/libX11.so
 &
sudo ln -s /lib/x86_64-linux-gnu/libX11.so.6.3.0 /usr/lib/libX11.so

both of them can't solve this.

**Comment by sammaple** [comment]
see issue #304

**Comment by MichaelEvans** [comment]
Anyone else having this issue?
