### ISSUE TITLE
two questions, thanks

### ISSUE THREAD

**Issue by lltboe** [andreasgal/B2G#308]
1. When I click the icon of a B2G application, is a new thread begin running or a process begin running? 
   I think it's same with Firefox browser, a new Tab Page/Browser Window with a new thread.
2. /system/b2g/b2g is a very great service, and I want to know where the source code of it. 
   Is ~/B2G/gecko/b2g/?

**Comment by benfrancis** [comment]
As I said in https://github.com/andreasgal/B2G/issues/311 can you please address your questions to the B2G mailing list https://lists.mozilla.org/listinfo/dev-b2g or in #B2G on irc.mozilla.org

These issues are for tracking requirements.

Thanks
