### ISSUE TITLE
About APP/Task Manager

### ISSUE THREAD

**Issue by lltboe** [andreasgal/B2G#309]
How does B2G manage the apps run, active close and change window state? 
I know it's javascript, but where is the source code?

Thank you!

**Comment by vingtetun** [comment]
On 28/06/2012 09:54, lltboe wrote:

> How does B2G manage the apps run, activity, close and change window state?
> I know it's javascript, but where is the source code?

All this code is in Gaia. And more precisely in 
apps/system/js/windows/window_manager.js

**Comment by lltboe** [comment]
Thank you!
