### ISSUE TITLE
where is the source code for app.launch()?

### ISSUE THREAD

**Issue by lltboe** [andreasgal/B2G#310]
In lastest B2G source code, B2G\gaia\apps\system\js\windows\window_manager.js, exists code follow:

---

  function start(origin) {
    if (isRunning(origin))
      return;

```
var app = Applications.getByOrigin(origin);

app.launch();
```

  }

---

I want get the source code for the method launch(), Thank you!

**Comment by vingtetun** [comment]
On 02/07/2012 11:36, lltboe wrote:

> In lastest B2G source code, B2G\gaia\apps\system\js\windows\window_manager.js, exists code follow:
> 
> ---
> 
>    function start(origin) {
>      if (isRunning(origin))
>        return;
> 
> ```
>  var app = Applications.getByOrigin(origin);
> 
>  app.launch();
> ```
> 
>    }
> 
> ---
> 
> I want get the source code for the method launch(), Thank you!

You want to digg a litlle bit but you want to read WebApps.js and 
WebApps.jsm in the source code of Gecko.

**Comment by lltboe** [comment]
I get the Webapps.jsm that you say, is B2G\gecko\dom\apps\src\Webapps.jsm?

After app.launch() done, it starts a new child thread? Or still in Main UI Thread?

**Comment by lltboe** [comment]
I get the Webapps.jsm that you say, is B2G\gecko\dom\apps\src\Webapps.jsm?

After app.launch() done, it starts a new child thread? Or still in Main UI Thread?

**Comment by wang-bin** [comment]
app is an object of mozIDOMApplication. defined in gecko/dom/interfaces/apps/nsIDOMApplicationRegistry.idl
