### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by alimd** [andreasgal/B2G#312]
I thing this project can change the web application world.

I'm a web dev and teacher.
I'm expert in JS and HTML/CSS
I was ios developer from 2008
I was android developer from 2010
I was webkit developer
and a mozilla lover ;)
I know we can fork and ... but revers engineering takes lot of time and energy.
join a team and work with a task organization system make we better.
I dont search for a job :D

I want join to this open project team and improve our skills and help to push web fwd ;)

Any suggestion for me?

Thank you in advance.

**Comment by alimd** [comment]
not only B2G project, everything connect to firefox os.

I remember, A few days after the release of chrome os i suggest to mozilla to start a gecko base of this idea.
but no anyone lissen to me :(

and now that idea with mobiles platform can explode my brain :D

**Comment by benfrancis** [comment]
Hi @alimd, have you seen https://wiki.mozilla.org/B2G/Hacking and https://wiki.mozilla.org/B2G/Hacking ?

Also, keep an eye on http://flyinformation.nfshost.com/bugsahoy/?b2g=1 for mentored bugs which can be worked on.

Please address any follow up questions to the B2G mailing list (https://lists.mozilla.org/listinfo/dev-b2g) or the #b2g channel on irc.mozilla.org rather than opening an issue here.

Thanks

**Comment by BrendanEich** [comment]
Cc'ing some folks who can guide you.

We do have on-ramps for new devs under construction, I believe.

/be

Ali Mihandoost wrote:

**Comment by BrendanEich** [comment]
Hi Ali,

We are all pretty busy with a milestone/deadline this Friday.  Sorry for not responding sooner.

There was just a thread on the mozilla.dev.b2g mailing list that you might take a look at.  Another person basically is asking the same question as you, "how do I get involved?".

```
https://groups.google.com/forum/#!topic/mozilla.dev.b2g/u-ryHvw_IYw/discussion
```

I hope that helps.  Find me (dougt) on irc.mozilla.org if you have any specific questions.  If I were you, I'd aim to get a desktop build of B2G/Gaia and start tinkering with it.

Doug

----- Original Message -----

**Comment by benfrancis** [comment]
Someone's having an identity crisis...

**Comment by BrendanEich** [comment]
Yikes, how did dougt's comment end up coming from me?

/be

**Comment by alimd** [comment]
@BrendanEich, @benfrancis  tank you very much.

@benfrancis, i dont understand what you mean about identity. !

**Comment by BrendanEich** [comment]
@alimd I think @benfrancis was referring to the curious way that Doug Turner's https://github.com/andreasgal/B2G/issues/312#issuecomment-7122619 seemed to come from me.

I wonder whether Doug replied to a forwarded email and that confused github.

/be
