### ISSUE TITLE
Make config-[phone] targets smarter about blob deps

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#33]
(Being smarter about build deps is a general enhancement for the build system, but ...)

I've found myself switching between sgs2<-->nexuss4g dev a fair amount.  Whenever I do that, I have to re-run the config-\* targets.  That part is fine; nothing needs to change there.

The problem is that both config targets always make me do the annoying "fetch blobs" step, whether or not I've already fetched them.  It would be great to skip that step if it's already been run (and the blobs are still present).

Maybe a little sentinel file that gets cleared on an explicit |make clean| or |make realclean| would be a close enough approximation.

**Comment by ThinkerYzu** [comment]
We can always fetch blob files into a distfiles/ subdirectory, and retrieve only files which is not existing in the directory from remote.  To implement this idea, we need a generic macro that download files for URLs with various protocol schemes.  The macro would invoke wget/git/hg/...etc, various tools accroding protocol scheme given in URL.

**Comment by joneschrisg** [comment]
Sadly, the only phone for which we have downloadable blobs is the nexuss4g, and this support was already added for the nexuss4g.
