### ISSUE TITLE
Installing gecko to /system/app breaks install-gecko target

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#39]
I did an install with latest and then |make install-gecko|.  The install succeeded, but afterwards (after restarting)
# pm path org.mozilla.fennec_cjones

package:/system/app/B2G.apk
# cat /proc/3245/maps

[snip]
4697f000-46980000 r--s 00000000 b3:09 14         /system/app/B2G.apk
[snip]

it appears that the old /system/app version is being used.

@michaelwu any ideas?  I would rather back out the system-install patch than break install-gecko.

**Comment by michaelwu** [comment]
Fixed. We now update the version code everytime we make gecko, so gecko will always think we're updating the system B2G with a newer one. A restart still appears to be required to switch away from system gecko, however.
