### ISSUE TITLE
Apparent race condition in initialization of GL stack

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#59]
CC @mwu, @jlebar, @shianyow

@mwu and @jlebar have noticed a problem in the gonk widget backend in which gecko can't draw to the screen after startup, leaving a black screen.  I've noticed a problem with the android widget backend in which gecko sometimes fails to create a GL layer manager, and has to fall back on CPU compositing (which _destroys_ performance of the home screen).

They sound like they might both be caused by the same underlying problem: failure to create a GL context around the time of startup, possibly due to a race condition.  I don't know what might cause this.  It'd be interesting to look at the android GL implementation and see what it does.  It might have a solution to this problem already.

**Comment by michaelwu** [comment]
I worked around this problem by disabling the addons manager. Apparently the addons manager does something which causes a black screen, but only if the addons code hasn't been startup cached.

**Comment by joneschrisg** [comment]
Um ... wow.  So maybe this affects firefox/android too?

**Comment by jlebar** [comment]
The fix has worked perfectly for me so far, fwiw.

**Comment by michaelwu** [comment]
Fennec on android with the xul frontend.. maybe. Not sure what's going on really.

**Comment by michaelwu** [comment]
I fixed some window visibility/invalidation/drawing issues in gonk. Now I don't have any issues with black screens. Can someone confirm? The addons manager must've triggered some sort of race that the code couldn't handle before.

**Comment by jlebar** [comment]
I'll let you know how it goes next time I rebuild and push, but it'll
be in a day or two.

On Tue, Nov 15, 2011 at 1:59 PM, Michael Wu
reply@reply.github.com
wrote:

**Comment by joneschrisg** [comment]
Since this only affects the b2g-android backend, it's low priority atm.
