### ISSUE TITLE
Enable PMU in sgs2 kernel

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#60]
This is needed to get oprofile working.  We cherry-picked two patches for the nexus s kernel

 https://github.com/cgjones/samsung-android-kernel/commit/ab2cbd6b0071edb63efb5b54e3d92c296ba34589
 https://github.com/cgjones/samsung-android-kernel/commit/4c9edf6e64a8567ab7a52226128bae4701c44281

Hopefully the same patches work with the sgs2 chip ...

**Comment by joneschrisg** [comment]
CC @shianyow

**Comment by shianyow** [comment]
The SGS2 kernel can work with oprofile and perf without needing these patches.

What we need is to patch glue/gonk/external/oprofile to add ARM Coretex-A9 support.
Should we wait new mozilla-b2g repo ready to create local fork for oprofile submodule?

**Comment by joneschrisg** [comment]
Are oprofile/perf able to use hardware events in the default sgs2 kernel?

What oprofile changes are needed for cortex-a9 support?  Is this support already upstream, so that we can merge it in?

**Comment by shianyow** [comment]
For oprofile, I was using cpu-cycles.
For perf, I tested some hardware events in "perf list", and seems they are working fine.

~ # perf stat -e cpu-cycles -e instructions -e cache-references ls /system
app         build.prop  framework   lost+found  usr
b2g         etc         home        media       vendor
bin         fonts       lib         tts         xbin

 Performance counter stats for 'ls /system':

```
       1178294 cpu-cycles                #    0.000 GHz                    
        558925 instructions              #    0.47  insns per cycle        
           501 cache-references                                            

   0.007755750 seconds time elapsed
```

~ #

**Comment by shianyow** [comment]
The Cortex-A9 patch was not included in gingerbread branch for "external/oprofile".

According to "http://android.git.linaro.org/gitweb?p=platform/external/oprofile.git;a=shortlog", the newer branches integrated the Cortex-A9 patch are ics-\* and master.  But it changed a lot (I think mostly should be upgrading to oprofile 0.9.6 and adding host tool builds). This change will introduce other changes to B2G source tree which based on gingerbread, such as adding libbfd, libiberty, libintl...

To patch only Cortex-A9 is simple, but we need to create local fork to do it, another way is to put a prebuilt oprofile binary to B2G repo temporarily.

**Comment by joneschrisg** [comment]
Great!

OK, let's just land the cortex-a9 patch.

**Comment by shianyow** [comment]
It's landed to git://github.com/mozilla-b2g/platform_external_oprofile.git
