### ISSUE TITLE
Multiple b2g .apk files causes "make flash" to fail

### ISSUE THREAD

**Issue by benfrancis** [andreasgal/B2G#62]
In the Makefile that was generated for the Samsung Galaxy SII, in the gecko-android-hack section there's the following line:

cp -p gecko/objdir-prof-android/dist/b2g-*.apk $(APP_OUT_DIR)/B2G.apk

My dist directory contained two matching .apk files "b2g-10.0a1.en-US.android-arm.apk" and "b2g-9.0a1.en-US.android-arm.apk"

As a result, this line attempts to copy multiple files to a single file target which generates the error "cp: target `~/Code/andreasgal/B2G/glue/gonk/out/target/product/galaxys2/system/app/B2G.apk' is not a directory" and stops make flash from running.

Removing the older .apk file fixes the problem, so perhaps this script should automatically pick the latest one somehow?

**Comment by jlebar** [comment]
I tried to fix this, but apparently only got halfway.

https://github.com/andreasgal/B2G/commit/65692103b70397489228001b42aad4f7cfab9e7a

While you're at it, you may want to add the |gecko| prerequisite back to gecko-gonk-hack.  I dunno why I removed it.
