### ISSUE TITLE
b2g-android sometimes doesn't start with a full screen

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#64]
Not sure what the underlying cause is.  Seems to be some kind of race condition.  Not terribly high priority.

Possibly related to #59.

**Comment by andreasgal** [comment]
We are abandoning Android.

**Comment by joneschrisg** [comment]
This is most likely an issue for old-fennec too, but since it's dying I don't think we care too much there either.  Ah well, unsolved mystery.
