### ISSUE TITLE
S3CFB_SET_VSYNC_INT spammed to logcat when screen turned off

### ISSUE THREAD

**Issue by jlebar** [andreasgal/B2G#70]
When I turn off the screen, the following message is spammed to logcat:

E/gralloc ( 2690): S3CFB_SET_VSYNC_INT enable failed

I think this is a relatively new issue, but I'm not sure.  qDot sees this too.

**Comment by joneschrisg** [comment]
I r+'d the fix for this today in bugzilla.

**Comment by adamxin** [comment]
would you give your fix?
