### ISSUE TITLE
Incorrect orientation in emulator with Android backend

### ISSUE THREAD

**Issue by justindarc** [andreasgal/B2G#76]
When launching the emulator after building B2G with the Android backend, the emulator window indicates portrait orientation, however, all display contents are rendered in landscape orientation as if the device were rotated 90 degrees clockwise.

**Comment by joneschrisg** [comment]
Yeah I've seen this too.  Not sure what's up.  CC @michaelwu @jlebar

**Comment by andreasgal** [comment]
we are about to kill the android backend, so we can probably forget about this

**Comment by joneschrisg** [comment]
We don't have orientation support in gonk yet so we're not going to know immediately whether it's affected.  But we can certainly re-file when needed.
