### ISSUE TITLE
Gecko Cloning fails with git error

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#77]
'make sync' (git submodule update --init ) fails with the following error. 

fatal: destination path 'gecko' already exists and is not an empty directory.
Clone of 'git://github.com/cgjones/mozilla-central.git' into submodule path 'gecko' failed

gecko/mozconfig symlink causes this issue. Moving the file to somewhere else allows you to continue the update

**Comment by jlebar** [comment]
Why was gecko/mozconfig created before git submodule update --init was run?

**Comment by arky** [comment]
I have no idea. Perhaps I had run 'make' or something?

**Comment by jlebar** [comment]
Could be.

I guess we could fix this by not creating the |gecko| folder during make.  I'm not sure this is worth worrying about, though.

**Comment by joneschrisg** [comment]
Please reopen if you run into this again.

**Comment by jhooda** [comment]
I am trying to run make sync on a fresh checkout and got this

Cloning into 'gecko'...
fatal: remote error: 
  Repository not found.
Clone of 'git://github.com/mozilla-b2g/mozilla-central.git' into submodule path 'gecko' failed
make: **\* [sync] Error 1

**Comment by jlebar** [comment]
@jhooda, yours is a different issue; please open a new ticket for it.

**Comment by jlebar** [comment]
@jhooda Also, are you sure you checked out https://github.com/mozilla-b2g/B2G/ and not https://github.com/andreasgal/B2G ?

**Comment by jhooda** [comment]
Hi Justin,

I'm positive I have used the mozilla-b2g link. Only caveat is that I had to restart "make sync" as it was interrupted. 

By the I am not authorized to file issues.

Thanks,

## Jagbir

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

Justin Lebar reply@reply.github.com wrote:

@jhooda Also, are you sure you checked out https://github.com/mozilla-b2g/B2G/ and not https://github.com/andreasgal/B2G ?

---

**Comment by jlebar** [comment]
Try ./repo sync.  I'm surprised |make sync| even works...

On Sun, Aug 5, 2012 at 9:04 PM, jhooda
reply@reply.github.com
wrote:

> Hi Justin,
> 
> I'm positive I have used the mozilla-b2g link. Only caveat is that I had to restart "make sync" as it was interrupted.
> 
> By the I am not authorized to file issues.
> 
> Thanks,
> 
> ## Jagbir
> 
> Sent from my Android phone with K-9 Mail. Please excuse my brevity.
>
