### ISSUE TITLE
Kill b2g-android (b2g on dalvik)

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#83]
b2g-gonk has now passed the milestone of being more functional than b2g-android, and additonally (though somewhat concerningly ...) gaia on b2g-gonk is generally more reliable than gaia on b2g-android.

The two major missing pieces in b2g-gonk are a settings controller and wifi or 3g access.  However, it's now quite clear that b2g-android isn't going to make it as our developer phone, so I think it can be safely killed off.  The one major pain point when doing so will be hacking on the web browser, but the web browser can easily be hacked in a b2g build installed on vanilla android, or on desktop.  Plus wifi should be working soon.

\o/

**Comment by andreasgal** [comment]
We should also kill the dependency on ANDROID_SDK and ANDROID_NDK at the same time.

**Comment by joneschrisg** [comment]
This one felt good.
