### ISSUE TITLE
INSTALL: Add 'make kernel'

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#86]
I think 'make kernel' is not mentioned in the Qemu section of the install file. 

make config-qemu
make 
make kernel 
./emu.sh

**Comment by joneschrisg** [comment]
Can you please update the documentation and send a pull request?  Thanks!

**Comment by arky** [comment]
Will do that. Along with few other changes to the INSTALL file.

**Comment by arky** [comment]
'make kernel' step is not needed. Closing the bug
