### ISSUE TITLE
To patch bionic

### ISSUE THREAD

**Issue by ThinkerYzu** [andreasgal/B2G#90]
I need to patch atoi() function of bionic.  rild from galaxy s2 need this patch to make data calls.  But, B2G has no its owned repository for  bionic.  So, some one should create a repository, or find other solution.

**Comment by joneschrisg** [comment]
@philikon is the new mozilla-b2g group ready?  We can fork under there.

**Comment by joneschrisg** [comment]
@ThinkerYzu you have the right permissions to create repositories for the mozilla-b2g account now.  I'll try to do it later tonight if you don't.

**Comment by michaelwu** [comment]
bionic has been forked and atoi has been patched.
