### ISSUE TITLE
 error: undefined reference to 'inflate'

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#92]
nsUConvDataModule.cpp
nsStaticXULComponents.cpp
nsUnicharUtils.cpp
nsBidiUtils.cpp
nsRDFResource.cpp
../../../../glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/../../../../arm-eabi/bin/ld: ../../modules/freetype2/.libs/libfreetype.a(ftgzip.o): in function ft_gzip_file_init:ftgzip.c(.text+0x260): error: undefined reference to 'inflateInit2_'
../../../../glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/../../../../arm-eabi/bin/ld: ../../modules/freetype2/.libs/libfreetype.a(ftgzip.o): in function ft_gzip_file_done:ftgzip.c(.text+0x2a6): error: undefined reference to 'inflateEnd'
../../../../glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/../../../../arm-eabi/bin/ld: ../../modules/freetype2/.libs/libfreetype.a(ftgzip.o): in function ft_gzip_file_reset:ftgzip.c(.text+0x332): error: undefined reference to 'inflateReset'
../../../../glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/../../../../arm-eabi/bin/ld: ../../modules/freetype2/.libs/libfreetype.a(ftgzip.o): in function ft_gzip_file_fill_output:ftgzip.c(.text+0x4c8): error: undefined reference to 'inflate'
collect2: ld returned 1 exit status
make[6]: **\* [libxul.so] Error 1
make[5]: **\* [libs_tier_platform] Error 2
make[4]: **\* [tier_platform] Error 2
make[3]: **\* [default] Error 2
make[2]: **\* [realbuild] Error 2
make[1]: **\* [build] Error 2
make: **\* [gecko] Error 2

**Comment by arky** [comment]
Wondering if this is caused by missing libpnglite-dev library?

**Comment by arky** [comment]
Installing expat package might fix this problem. Can someone confirm this

**Comment by joneschrisg** [comment]
I can't reproduce this with a clean b2g build.

Can you let us know what commands you used to configure your build, which build type you're using (android or gonk), and which SDK/NDK versions you're using?  Thanks!

**Comment by arky** [comment]
Build Machine Information: 
$ lsb_release -a
LSB Version:    core-2.0-ia32:core-2.0-noarch:core-3.0-ia32:core-3.0-noarch:core-3.1-ia32:core-3.1-noarch:core-3.2-ia32:core-3.2-noarch:core-4.0-ia32:core-4.0-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 11.10
Release:    11.10
Codename:   oneiric

Build Commands:
make sync
make config-qemu
make gonk 
make

**Comment by joneschrisg** [comment]
OK, I was trying a galaxy-s2 build.  Will give a qemu build a try.

**Comment by joneschrisg** [comment]
The qemu build wfm too :/.  Maybe try a |make clean| and then re-run the steps above?

**Comment by arky** [comment]
Thanks, I'll try that.

**Comment by arky** [comment]
Thanks. Closing this issue.
