### ISSUE TITLE
C compiler cannot create executables.

### ISSUE THREAD

**Issue by arky** [andreasgal/B2G#93]
$make clean
$ make 
(Results in this new error) 

checking whether the C compiler (/home/arky/src/B2G/gecko/objdir-prof-android/../../glue/gonk/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-gcc -mandroid -fno-short-enums -fno-exceptions  -mandroid -L/home/arky/src/B2G/gecko/objdir-prof-android/../../glue/gonk/out/target/product/generic/obj/lib -Wl,-rpath-link=/home/arky/src/B2G/gecko/objdir-prof-android/../../glue/gonk/out/target/product/generic/obj/lib --sysroot=/home/arky/src/B2G/gecko/objdir-prof-android/../../glue/gonk/out/target/product/generic/obj/ -llog ) works... no
configure: error: installation or configuration problem: C compiler cannot create executables.
**\* Fix above errors and then restart with               "make -f client.mk build"
make[3]: **\* [configure] Error 1
make[2]: **\* [/home/arky/src/B2G/gecko/objdir-prof-android/Makefile] Error 2
make[1]: **\* [build] Error 2

Full logs:
http://paste.ubuntu.com/773480/

**Comment by michaelwu** [comment]
Try make gonk first before make. It's a temporary workaround until we fix some circular dependencies.

**Comment by arky** [comment]
Thanks!
