### ISSUE TITLE
backlight should be controled via libhardware.so

### ISSUE THREAD

**Issue by andreasgal** [andreasgal/B2G#94]
see hardware/libhardware/include/hardware/lights.h

This will make sure we use the right abstraction if some phones use a different kernel interface.

**Comment by andreasgal** [comment]
While at it, we should expose the other light types via GonkHal.cpp as well:

#define LIGHT_ID_BACKLIGHT          "backlight"
#define LIGHT_ID_KEYBOARD           "keyboard"
#define LIGHT_ID_BUTTONS            "buttons"
#define LIGHT_ID_BATTERY            "battery"
#define LIGHT_ID_NOTIFICATIONS      "notifications"
#define LIGHT_ID_ATTENTION          "attention"
#define LIGHT_ID_BLUETOOTH          "bluetooth"
#define LIGHT_ID_WIFI               "wifi"

**Comment by andreasgal** [comment]
@jlebar want to take this one, or should I find someone else?

**Comment by joneschrisg** [comment]
I thought this had been filed in bugzilla but it hasn't.  Let's track this from bug 673923.

**Comment by jlebar** [comment]
I'm happy to do it, but this might be a good project for someone starting out, if it's not urgent.  I can review and help out.

**Comment by straus** [comment]
I'm going to look at it.

**Comment by jlebar** [comment]
Let me know how I can help!

**Comment by andreasgal** [comment]
As @cgjones pointed out, the patch for this should go into mozilla-central via bugzilla.

**Comment by straus** [comment]
On 12/19/11 10:55 AM, Justin Lebar wrote:

> Let me know how I can help!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/andreasgal/B2G/issues/94#issuecomment-3204900
> Hello Justin -
>    I've been digging into Vibrate and Battery, since they seemed similar 
> to adding in lights, though I've also been looking at radio and audio.  
> The two paths seem to be:

```
 Add Lights into the HAL.  This is done by adding functionality into 
```

the hal/gonk and then calling the hal_impl version from Hal.cpp.  Do I 
need to stub out the same functions in hal/linux, windows, fallback, 
android, just so those will compile?  Also, do I need to do the loop 
back in hal/sandbox?
     From there, create a manager in dom/lights (similar to the battery 
manager already there).  Then add the new interfaces into 
dom/base/Navigator.cpp and idl.

```
 The alternative is to add in to dom/system/b2g (or maybe create a 
```

new dom/lights/b2g) and create and idl there and either directly handle 
the lights or create a proxy or daemon to control the lights (though I 
think that is over kill in this case).

```
 The latter seems more self contained and probably cleaner.  
```

However, it is a bit more opaque as to how it all hooks up and becomes 
available to the javascript.  Probably need to read more of the XPCOM 
interface.
     Thoughts?
-Jim Straus

**Comment by joneschrisg** [comment]
Let's continue this discussion and do the work in https://bugzilla.mozilla.org/show_bug.cgi?id=712378 .
