### ISSUE TITLE
Error: " ** Don't have a product spec for: 'full_maguro'"

### ISSUE THREAD

**Issue by joneschrisg** [andreasgal/B2G#98]
$ make gonk
rm -rf /home/cjones/mozilla/b2g/glue/gonk/out/target/product/maguro/system/home
mkdir -p /home/cjones/mozilla/b2g/glue/gonk/out/target/product/maguro/system/home
cp -r gaia/\* /home/cjones/mozilla/b2g/glue/gonk/out/target/product/maguro/system/home
including device/samsung/crespo4g/vendorsetup.sh
including device/samsung/crespo/vendorsetup.sh
including device/samsung/galaxys2/vendorsetup.sh
including device/toro/maguro/vendorsetup.sh
build/core/config.mk:136: **\* No config file found for TARGET_DEVICE maguro.  Stop.

*\* Don't have a product spec for: 'full_maguro'
*\* Do you have the right repo manifest?

make: **\* [gonk] Error 1

Will look in more detail tomorrow, running out of steam.

**Comment by joneschrisg** [comment]
CC @andreasgal 

Looks like we're missing a BoardConfig.mk.  Missing |git add|?

**Comment by joneschrisg** [comment]
OK, that'll need some work.  Let's try to hack it tomorrow.

**Comment by mvines** [comment]
Stale issue?

**Comment by joneschrisg** [comment]
Yes, thanks.
