### ISSUE TITLE
zImage: no such file or directory, when building qemu

### ISSUE THREAD

**Issue by jonallengriffin** [andreasgal/B2G#99]
The full error is:

Install system fs image: out/target/product/generic/system.img
Installed file list: out/target/product/generic/installed-files.txt
make[1]: Leaving directory `/home/jgriffin/jB2G/glue/gonk'
cp -p boot/kernel-android-qemu/arch/arm/boot/zImage \
        /home/jgriffin/jB2G/glue/gonk/device/qemu/kernel
cp: cannot stat`boot/kernel-android-qemu/arch/arm/boot/zImage': No such file or directory
make: **\* [kernel-qemu] Error 1

This occurs after:  'make clean', 'make sync', 'make config-qemu', 'make gonk', and then 'make'

**Comment by malini** [comment]
by bit he meant build

On Thu, Dec 22, 2011 at 5:56 PM, Jonathan Griffin <
reply@reply.github.com

> wrote:
> 
> The full error is:
> 
> Install system fs image: out/target/product/generic/system.img
> Installed file list: out/target/product/generic/installed-files.txt
> make[1]: Leaving directory `/home/jgriffin/jB2G/glue/gonk'
> cp -p boot/kernel-android-qemu/arch/arm/boot/zImage \
>                /home/jgriffin/jB2G/glue/gonk/device/qemu/kernel
> cp: cannot stat`boot/kernel-android-qemu/arch/arm/boot/zImage': No such
> file or directory
> make: **\* [kernel-qemu] Error 1
> 
> This occurs after:  'make clean', 'make sync', 'make config-qemu', 'make
> gonk', and then 'make'
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/andreasgal/B2G/issues/99

## 

Regards,
Malini

**Comment by joneschrisg** [comment]
Does it work if you |make kernel| before |make gonk|?

Edit: it does not.

**Comment by joneschrisg** [comment]
Are you building b2g-android or b2g-gonk?  I'm building b2g-android atm, will report back.

**Comment by joneschrisg** [comment]
This reproduces in b2g-android too.  Investigating.

**Comment by joneschrisg** [comment]
CC @andreasgal 

Regressed by https://github.com/andreasgal/B2G/commit/a9a073e47208c0fb3eefad8676cb6dde083bcd44#Makefile

**Comment by joneschrisg** [comment]
ece604d9b8ca9c16bb6be56ce28784b59c4651c6
